### PR TITLE
deterministicly sort C variable types

### PR DESCRIPTION
**Pull request by demoray**
Decompiling the same binary should always result in the same decompilation.  As is, identifying variable types is not determinstic.  This PR fixes the sorting of variable types to be deterministic.

Example:

```python deterministic-variable-names.py
#!/usr/bin/env python

import difflib
import logging
import sys

from sortedcontainers import SortedDict

import angr
from angr.analyses.decompiler.decompilation_options import (
    PARAM_TO_OPTION,
    DecompilationOption,
)

logging.basicConfig(level=logging.CRITICAL, force=True)


def analyze_binary(binary_path):
    project = angr.Project(binary_path, auto_load_libs=False)
    cfg = project.analyses.CFGFast(normalize=True)
    function = cfg.functions[4203344]
    function.normalize()
    decomp = project.analyses.Decompiler(func=function, cfg=cfg, options=[(PARAM_TO_OPTION["show_casts"], False)])
    return decomp.codegen.text


def main():
    result = None
    for i in range(10):
        print(f"run {i}")
        latest = analyze_binary(sys.argv[1]).split("\n")
        if result is None:
            result = latest
        elif result != latest:
            for diff in difflib.unified_diff(result, latest):
                print(diff)
            break

if __name__ == "__main__":
    main()
```

When run the above example python with a locally built version of `BitBlaster.exe` from the Cyber Grand Challenge will generate the following output:

```
❯ python deterministic-variable-names.py ./BitBlaster.exe
run 0
run 1
---

+++

@@ -22,7 +22,7 @@

     unsigned int v15;  // [bp-0x270]
     unsigned int v16;  // [bp-0x26c]
     unsigned short v17;  // [bp-0x268]
-    unsigned int v18;  // [bp-0x64], Other Possible Types: char
+    char v18;  // [bp-0x64], Other Possible Types: unsigned int
     unsigned int v19;  // [bp-0x60]
     unsigned int v20;  // [bp-0x58]
     struct_0 *v21;  // [bp-0x14]

```

### CODE REVIEW

**Comment by demoray** [comment]
Binary used in example.

[bitblaster.zip](https://github.com/user-attachments/files/16604808/bitblaster.zip)

**Comment by demoray** [comment]
> This is a great PR! Thanks for your contribution. Would you be able to add a small testcase for this to: https://github.com/angr/angr/blob/master/tests/analyses/decompiler/test_decompiler.py
> 
> Running it in a loop a few times is _probably_ the best way. Ideally, pick a small function so the runtime is not too insane. You can add your binary to: https://github.com/angr/binaries in a PR.

PR for binary: https://github.com/angr/binaries/pull/123

Once this is merged, I'll update the integration test to use it.

**Comment by demoray** [comment]
> Thank you, it's been merged.

Test case has been added.

**Comment by mahaloz** [comment]
@demoray in https://github.com/angr/angr/pull/4746/commits/8c4a310ca72331fbf51b2eb31b8b1523845b67f9 I moved CFG construction out of the loop, but now it seems the decompilation is nondeterministic again. Would be able to explain why? 

From the code you changed, it should not be effected. Or did I miss a cache used somewhere...

**Comment by demoray** [comment]
> @demoray in [8c4a310](https://github.com/angr/angr/commit/8c4a310ca72331fbf51b2eb31b8b1523845b67f9) I moved CFG construction out of the loop, but now it seems the decompilation is nondeterministic again. Would you be able to explain why?
> 
> From the code you changed, it should not be effected. Or did I miss a cache used somewhere...

The update to the loop you made changed a _large_ number of things beyond what my change addressed.

If we use this updated test script:
```python
#!/usr/bin/env python

import difflib
import logging
import sys

import angr
from angr.analyses.decompiler.decompilation_options import (
    PARAM_TO_OPTION,
    DecompilationOption,
)

logging.basicConfig(level=logging.CRITICAL, force=True)


def analyze_binary(binary_path):
    return decomp.codegen.text


def main():
    result = None

    project = angr.Project(sys.argv[1], auto_load_libs=False)
    cfg = project.analyses.CFGFast(normalize=True)
    function = cfg.functions[4203344]
    function.normalize()
    for _ in range(10):
        decomp = project.analyses.Decompiler(func=function, cfg=cfg, options=[(PARAM_TO_OPTION["show_casts"], False)])
        if result is None:
            result = decomp.codegen.text.split("\n")
            continue

        latest = decomp.codegen.text.split("\n")

        if result != latest:
            for diff in difflib.unified_diff(result, latest):
                print(diff)
            break


if __name__ == "__main__":
    main()
```

we see the following output:
```
--- 

+++ 

@@ -5,6 +5,8 @@

 int sub_402350()
 {
     unsigned int v0;  // [bp-0x334]
+    unsigned int s_c;  // [bp-0xc]
+    unsigned int ir_30;  // eax
     char v1;  // [bp-0x330], Other Possible Types: unsigned int
     unsigned short v2;  // [bp-0x2a4]
     unsigned short v3;  // [bp-0x2a0]
@@ -32,20 +34,6 @@

     char v25;  // [bp-0x5]
     unsigned int v26;  // [bp-0x4]
     char v27;  // [bp+0x0]
-    unsigned int v29;  // ecx
-    unsigned int v30;  // edx
-    unsigned int v31;  // ebx
-    unsigned int v32;  // esi
-    unsigned int v33;  // edi
-    unsigned short v34;  // ss
-    unsigned short v35;  // cs
-    unsigned short v36;  // ds
-    unsigned short v37;  // es
-    unsigned short v38;  // fs
-    unsigned short v39;  // gs
-    unsigned int v40;  // d
-    unsigned int v41;  // id
-    unsigned int v42;  // ac
     unsigned int v43;  // ebp
 
     v26 = &v27;
@@ -53,18 +41,18 @@

     {
         sub_402230();
         v11 = memset(&v1, 0);
-        v10 = v29;
-        v9 = v30;
-        v8 = v31;
-        v7 = v32;
-        v6 = v33;
-        v17 = v34;
-        v14 = v35;
-        v5 = v36;
-        v4 = v37;
-        v3 = v38;
-        v2 = v39;
-        v0 = [D] x86g_calculate_eflags_all(0x3<32>, BaseOffset(stack_base, -828), 0xc<32>, 0x0<32>) | 514 | v40 & 0x400 | v41 * 0x200000 & 0x200000 | v42 * 0x40000 & 0x40000;
+        v10 = ecx<4>;
+        v9 = edx<4>;
+        v8 = ebx<4>;
+        v7 = esi<4>;
+        v6 = edi<4>;
+        *(&v17) = ss<2>;
+        *(&v14) = cs<2>;
+        *(&v5) = ds<2>;
+        *(&v4) = es<2>;
+        *(&v3) = fs<2>;
+        *(&v2) = gs<2>;
+        v0 = [D] x86g_calculate_eflags_all(0x3<32>, BaseOffset(stack_base, -828), 0xc<32>, 0x0<32>) | 514 | d<4> & 0x400 | id<4> * 0x200000 & 0x200000 | ac<4> * 0x40000 & 0x40000;
         v15 = v0;
         v1 = 65537;
         v13 = *(&v27);
@@ -82,7 +70,7 @@

         v21 = &v18;
         v22 = &v1;
         SetUnhandledExceptionFilter(NULL);
-        v23 = UnhandledExceptionFilter(&v21);
+        s_c = UnhandledExceptionFilter(&v21);
         if (v23)
         {
             v43 = v26;
@@ -95,7 +83,7 @@

         }
         else
         {
-            sub_402230();
+            ir_30 = sub_402230();
             v43 = v26;
             return;
         }
```

**Comment by mahaloz** [comment]
Wow, that's... bad. Welp, a new TODO for a future version of myself.

**Pull request merged**
