### PR TITLE
Added _parent to list of pickled attributes in PathHistory

### PR DESCRIPTION
**Pull request by juk80x**
Needed _parent to the list of attributes in _set_state in order to be able to pickle a path. 

Also determined that TRACK_ACTION_HISTORY must be set or else the _events attribute will be a weakref which will cause the following error, when you attempt to pickle the path.

``` python
ReferenceError: weakly-referenced object no longer exists
```

### CODE REVIEW

**Comment by rhelmot** [comment]
It's important that pickling works when TRACK_ACTION_HISTORY is disabled. Can we try/catch this error and then just replace the weakref with None or an empty list?

**Comment by juk80x** [comment]
Where would you suggest putting the try/catch? It doesn't occur until I call pickle.dump(). Is there an implicit call to _record_state or __getstate__ when that happens?

**Comment by rhelmot** [comment]
Can it be caught in `__setstate__`? If not I'd recommend doing an explicit check in `__getstate__` to see if you're about to pickle up a weak reference, and then instead pickle or the empty list.

**Comment by juk80x** [comment]
try/catch is not catching the ReferenceError, when I set it in __setstate__. It appears that when __setstate__ is called no error is thrown because the object exists at the time. As the object is pickled, though, the number of references to the object is zero and the object is destroyed. At this point, the ReferenceError is thrown. More than likely this occurs within the pickle code itself. 

The only option I can see is to always set _events to () in __setstate__ when TRACK_ACTION_HISTORY is not set  (i.e. don't pickle it as part of the state) or never set _events to a weakref.proxy at all.

**Comment by zardus** [comment]
Setting `history._events` to a blank tuple if `TRACK_ACTION_HISTORY` is not set sounds like a reasonable measure in the meantime. The semantic meaning of `TRACK_ACTION_HISTORY` is, nowadays, that actions aren't guaranteed to stay around without it. This is one such case of actions not staying around.

**Comment by juk80x** [comment]
Not sure how I check for options inside __getstate__. There does not appear to be an attribute that contains the state or its options.

**Comment by zardus** [comment]
IIRC, this either got cherry-picked in, or the change was done upstream in the meantime. In either case, pickling of paths seems to work properly now (and there are even testcases that ensure this works, for the `Spiller` exploration technique). Thanks for pointing this out!

**Pull request closed without merging**
