### PR TITLE
Re/test case fixes

### PR DESCRIPTION
**Pull request by WGibbs15**

### CODE REVIEW

**Comment by ltfish** [comment]
Can you rebase?

**Comment by WGibbs15** [comment]
Will do 👍

**Comment by ltfish** [comment]
This PR is still marked as WIP. Is it ready to be reviewed/considered?

**Comment by WGibbs15** [comment]
I'm going to close this pull request.  The merge conflicts are more intertwined than I originally thought, so it'll be easier to apply fixes on a new branch based off the current re/static_analysis_memory_model than trying to rebase this branch.

**Pull request closed without merging**
