### PR TITLE
Update test_argv.py

### PR DESCRIPTION
**Pull request by trz19991228**
make less ugly

### CODE REVIEW

**Comment by rhelmot** [comment]
You seem to misunderstand how we run our tests - yes, we have `if __name__ == '__main__':` at the bottom of every test file to facilitate running the tests as scripts, but the standard, what CI uses, is running the tests through nose/nose2. To this end, you can't just have a function named `test` which takes a parameter, as tests must not take parameters. Instead, you can do something like this:

```
def run_test(arch):
    ...

def test_argv():
    for arch in arches:
        yield run_test, arch
```

and then nose will correctly run `run_test` with each of the members of `arches`.

**Comment by trz19991228** [comment]
> You seem to misunderstand how we run our tests - yes, we have `if __name__ == '__main__':` at the bottom of every test file to facilitate running the tests as scripts, but the standard, what CI uses, is running the tests through nose/nose2. To this end, you can't just have a function named `test` which takes a parameter, as tests must not take parameters. Instead, you can do something like this:
> 
> ```
> def run_test(arch):
>     ...
> 
> def test_argv():
>     for arch in arches:
>         yield run_test, arch
> ```
> 
> and then nose will correctly run `run_test` with each of the members of `arches`.

thank you!

**Comment by twizmwazin** [comment]
One concern I have for this PR is that nose 1 test generators are not supported in python's built in unittest framework. We are currently using nose2 to run the tests, but I don't think that we should be refactoring tests to be non-compliant with unittest. I agree that the code consolidation is an improvement, but I think we should look for a unittest-compliant solution.

Additionally, with unittest we can replace everything under `if __name__ == "__main__":` with `unittest.main()`.

**Comment by ltfish** [comment]
> nose 1 test generators are not supported in python's built in unittest framework

Too bad, but yes, we are moving away from nose 1. I believe this file can be made prettier without relying on generators.

**Pull request closed without merging**
