### PR TITLE
ANY_FILE_MIGHT_EXIST option for open

### LINKED ISSUE #3889: stat on non-existing file
### Description

When symbolically executing the following binary, angr does not execute the if-clause and explores only the else-branch with output "nothing\n". However, when executing the binary it prints "c0de\n".

Binary:

[stat_test.zip](https://github.com/angr/angr/files/11138282/stat_test.zip)

The code is here:

```C
#include <stdio.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

int main(int argc, char **argv) {
    struct stat statbuf;
    if (stat("FILE_DOES_NOT_EXIST.txt", &statbuf) < 0) {
        printf("c0de\n");
    } else {
        printf("nothing\n");
    }
    return 0;
}
```

### Steps to reproduce the bug

I am actually not sure if this is a bug or just needs some different configuration. You can use the following python script:

```python
import angr
p = angr.Project("stat_test")
simgr = p.factory.simgr()
simgr.explore(find = lambda s: s.posix.dumps(1) == b'c0de\n')
# <SimulationManager with 1 deadended>
simgr2 = p.factory.simgr()
simgr2.explore(find = lambda s: s.posix.dumps(1) == b'nothing\n')
# <SimulationManager with 1 found>
```

Expected: explore finds both c0de and nothing.

### Environment

Just the default.

### Additional context

This comes from the https://github.com/lks9/src-tracer, when trying to replay the busybox binary, see also #3883. The code above is simpler but bears the same problem I have when replaying a trace I recorded from busybox. Busybox wants to open `/etc/busybox.conf` which does not exist on my computer, so the syscall `SYS_stat` returns `-2`.

I am not using `state.fs.mount` for a concrete filesystem because I want to keep the filesystem abstract/symbolic.

### PR DESCRIPTION
**Pull request by lks9**
* Fixes the `stat` implementation (fixes  #3889)
* Adds ANY_FILE_MIGHT_EXIST options
* Now the result of `open`, `fopen`, `fdopen` and `stat` can depend on a symbolic value `file_exists` when ALL_FILES_EXIST=False and ANY_FILE_MIGHT_EXIST=True
* Corrected `struct stat` element order for amd64. I got `offset st_mode: 18` and `offset st_nlink: 10`. So I switched `st_mode` and `st_nlink` in `angr/procedures/linux_kernel/fstat.py` for amd64.

  Try it yourself:
  ```C
    printf("offset st_dev: %lx\n", (long) offsetof(struct stat, st_dev));
    printf("offset st_ino: %lx\n", (long) offsetof(struct stat, st_ino));
    printf("offset st_mode: %lx\n", (long) offsetof(struct stat, st_mode));
    printf("offset st_nlink: %lx\n", (long) offsetof(struct stat, st_nlink));
    printf("offset st_uid: %lx\n", (long) offsetof(struct stat, st_uid));
    printf("offset st_gid: %lx\n", (long) offsetof(struct stat, st_gid));
    printf("offset st_rdev: %lx\n", (long) offsetof(struct stat, st_rdev));
    printf("offset st_size: %lx\n", (long) offsetof(struct stat, st_size));
    printf("offset st_blksize: %lx\n", (long) offsetof(struct stat, st_blksize));
    printf("offset st_blocks: %lx\n", (long) offsetof(struct stat, st_blocks));
    printf("offset st_atim: %lx\n", (long) offsetof(struct stat, st_atim));
    printf("offset st_mtim: %lx\n", (long) offsetof(struct stat, st_mtim));
    printf("offset st_ctim: %lx\n", (long) offsetof(struct stat, st_ctim));
  ```

sync angr/binaries#106

### CODE REVIEW

**Comment by lks9** [comment]
From my side, this PR is ready! Especially tests like `fd == -1` were to be tricky, because `fd = state.solver.eval(fd_symbolic)` always outputs a large positive integer instead of `-1`. But I hope that I got it all right...

Feel free to change anything that can improve the code quality before merging.

**Comment by lks9** [comment]
> I can't check right now, but isn't there a signed=True you can set on calls to eval?

No, there isn't. I also checked the documentation.

```
TypeError: _eval() got an unexpected keyword argument 'signed'
```

**Comment by lks9** [comment]
Ok I solved the `fd != -1` problem by sticking to `0 < fd and fd <= max_fds` or `concr_fd != -1 and concr_fd == fd`.

**Comment by lks9** [comment]
I suppose the failed decompiler test has nothing to do with this PR. I have not touched anything there.

**Comment by ltfish** [comment]
@rhelmot ping?

**Review by rhelmot — APPROVED** [review]

**Pull request merged**
