### PR TITLE
Fix broken veritesting implementation

### PR DESCRIPTION
**Pull request by Kyle-Kyle**
~~a hack to make veritesting work again.~~

~~warning. it uses strong reference in `state_hierarchy`~~

### CODE REVIEW

**Comment by Kyle-Kyle** [comment]
if you are considering merging this. I'll write a testcase.

**Comment by Kyle-Kyle** [comment]
this was written a long time ago. I think only enabling `state_hierarchy` within `veritesting` will be an ideal solution

**Comment by rhelmot** [comment]
I really don't know anything about veritesting... I wish I could help

**Comment by ltfish** [comment]
@Kyle-Kyle is the current test case of veritesting on master broken?

**Comment by Kyle-Kyle** [comment]
it actually doesn't check the correctness of veritesting.
basically, the current testcase makes sure there will be a solution. but it can be generated by naive state merging.

**Comment by ltfish** [comment]
Yeah I remember we discussed this in the past. Can you provide a test case that ensures Veritesting is working as expected?

**Comment by Kyle-Kyle** [comment]
yeah sure

**Comment by luke-croak** [comment]
I tried testing your pull request on a problem with veritesting (previously working). I received a type error where it was trying to add a 'NoneType' and an 'int' together in "storage/memory_mixins/paged_memory/pages/ultra_page.py" in line 112. The error seems to have originated in "veritesting.py" with merging, line 235 "new_manager = self._execute_and_merge(s)"

**Comment by luke-croak** [comment]
Sure. This is the script and binary.

[Testing.zip](https://github.com/angr/angr/files/5846332/Testing.zip)

**Comment by luke-croak** [comment]
I pulled your updated branch and it ran till completion. However, it said there was no solutions, when previously it had found solutions.

**Comment by Kyle-Kyle** [comment]
yeah. I'm investigating this issue. It might be because my fix is wrong

**Comment by Kyle-Kyle** [comment]
interestingly. my old code works out of the box.
I'm guessing there is something wrong with the `merge` implementation of `ultra_page`.
I have no idea how that works, can you have a look at that when you are free? @rhelmot 
My old code is at https://github.com/Kyle-Kyle/angr/tree/veritesting_test

**Comment by luke-croak** [comment]
Does your old code work out of the box on the script and binary I sent? When I run it on my computer there seem to be some errors.

**Comment by Kyle-Kyle** [comment]
it's just because of API change during the days. But it works on my old build

**Comment by Kyle-Kyle** [comment]
@rhelmot now veritesting is fixed because of the state_hierarchy fix. I enhanced the veritesting tests to make sure the results are actually from veritesting.

**Comment by Kyle-Kyle** [comment]
what a rabbit hole. The bug is actually in the ancient history plugin code. Basically, the history plugin of a merged state will be corrupted after merging because it sets recent_actions before processing recent_constraints, which clears `self.recent_constraints`. When veritesting wants to do another state merge on a merged state, weird stuff happens: it may produce weird merging constraints (because the `state.history.recent_constraints` is corrupted), which in turn corrupts memory because the memory page merging logic depends on the constraints. The end results is that it will concretize a memory when the memory should be a conditional memory (stuff like `1 if blah else 0`).
I have no idea why my old code worked.
But anyway, the bug is fixed now.

**Comment by rhelmot** [comment]
Seems you broke one test case :(

**Comment by Kyle-Kyle** [comment]
@rhelmot It seems claripy fails to simplify this constraint set
~~~
[[<SAO <Bool BoolS(cond_0_0_-1)>>, <SAO <Bool BoolS(cond_0_0_-1)>>], [<SAO <Bool BoolS(cond_1_1_-1)>>, <SAO <Bool !BoolS(cond_0_0_-1)>>]]
~~~
I don't know how to fix it properly. But I can hack a patch

**Comment by rhelmot** [comment]
We never do cross-constraint simplification unless you call state.simplify() explicitly. Why do you need it to be simplified?

**Comment by Kyle-Kyle** [comment]
I think you added the simplify-by-default logic at https://github.com/angr/angr/commit/cd9d9bf5e36c6bbd63e031ee30bfd34936fb855f

**Comment by Kyle-Kyle** [comment]
@rhelmot can you review this?

**Comment by rhelmot** [comment]
Do you need this merged in tandem with your other PRs?

**Comment by Kyle-Kyle** [comment]
It is not urgent. So, we can merge it after fixing everything

**Comment by Kyle-Kyle** [comment]
@rhelmot  thanks!

**Pull request merged**
