### PR TITLE
fix(requirement)should update to latest

### PR DESCRIPTION
**Pull request by serfend**
version should not FREEZE for common use.
```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                        
angr 9.2.4 requires unicorn==1.0.2rc4, but you have unicorn 1.0.3 which is incompatible.
```

### CODE REVIEW

**Comment by rhelmot** [comment]
I'll approve CI for you, but it will fail badly. See https://github.com/angr/angr/issues/2541 and https://github.com/angr/angr/pull/3298 and https://github.com/angr/angr/pull/3382

**Comment by serfend** [comment]
oh , i havent notice that latest is broken version that v2 , how about use `unicorn 1.0.3` instead

**Comment by rhelmot** [comment]
Also broken. Even upgrading one single rc forward breaks our CI...

**Comment by dnivra** [comment]
Fixed in #3598. angr now supports unicorn 2.0.1.

**Pull request closed without merging**
