### PR TITLE
New exploration technique: Memory watcher

### PR DESCRIPTION
**Pull request by bannsec**
Pretty simple little memory watcher. Allows you to specify minimum amount of memory prior to stopping, otherwise it will stop at 95% memory utilization by default.

### CODE REVIEW

**Comment by ltfish** [comment]
Awesome stuff! Can you please add a simple test case to make sure we don't accidentally break this with future commits?

**Comment by rhelmot** [comment]
How do you suggest something that we can only test by running the system out of memory

**Comment by bannsec** [comment]
I'll add a test for the same way i tested locally. Specifically, letting simgr run for a bit with the normal MemoryWatcher (95% part), then change the min memory in the technique to something crazy high (10TB?) and the next step of simgr should bump all those paths over.

**Comment by ltfish** [comment]
I was just thinking of a smoketest that uses this exploration technique to do some light path exploration (to make sure our way of using `psutil` works, for example). We definitely don't want to consume all memory on our CI boxes :)

**Comment by Kyle-Kyle** [comment]
Probably you would like to use `complete` function?
And in documentation, we should say explicitly that it is not guaranteed that `angr` will use memory less than the limit.
Because there could be such a case that `angr` is already using memory close to the limit, and it tries to run `step` and get stuck in `claripy` and starting using much more memory than the limit. That could happen if path predicates are too complicated, if I understand correctly.

**Comment by bannsec** [comment]
Correct on the possibility of it using more memory than expected. It's definitely not a perfect solution but should work in many cases.

**Comment by bannsec** [comment]
Ok, added a test for it. Using the veritesting binary since it branches.

**Comment by rhelmot** [comment]
Looks great! thanks!

**Pull request merged**
