### PR TITLE
Replace cooldict dependency with collections.ChainMap

### PR DESCRIPTION
**Pull request by ConnorNelson**
cooldict is lame, lets use the standard library's collections.ChainMap!

### CODE REVIEW

**Comment by rhelmot** [comment]
it looks like this can result in an infinite recursion error - possibly due to a loop in the chain?

**Comment by ConnorNelson** [comment]
It seems that the ChainMap is getting too recursively deep, and exceeding python's default recursion limit. Instead of recursively constructing the ChainMap, we can just flatten it at each branch.

**Comment by rhelmot** [comment]
https://docs.python.org/3/library/collections.html#collections.ChainMap.new_child

**Comment by rhelmot** [comment]
I do like that this effectively nukes all mystery about how cooldict works. It does make me worry about whether there is performance degradation over the course of long paths though...

**Comment by ConnorNelson** [comment]
Yeah, the testcase fails for `sys.setrecursionlimit(1406)`, but succeeds for `sys.setrecursionlimit(1407)`. 

> https://docs.python.org/3/library/collections.html#collections.ChainMap.new_child

And I hadn't noticed that method, that is perfect!

> I do like that this effectively nukes all mystery about how cooldict works. It does make me worry about whether there is performance degradation over the course of long paths though...

I agree. I think that there is something very clearly wrong that we are managing potentially 1000s of dictionaries, which seriously degrades read speeds since we need to iterate until we find a dictionary with the key. I'm trying to understand cooldict, and it doesn't seem that it does anything special to manage this issue; it just black boxed it away. 

Do some of these ancestor `SimPagedMemory` instances get dropped at some point as the exploration progresses? It seems that we could potentially start opportunistically merging these backing dicts for performance gains (at least as far as lookups are concerned).

**Comment by rhelmot** [comment]
@zardus paging your knowledge of how this shit works

**Pull request merged**
