### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by axt**
Hi! I have created some small patches:

- cfg_base.py: it is the most important of the 3 change: I think this was maybe a typo, or I didnt understand the purpose of the code, please review it!

- cfg_accurate.py: path.steps() calls were missing, so that part of the code always throws an exception. (I'm not sure if that part of code is used currently)

- ddg.py: was not changed when knowledge_base was refactored, its just trivial changes

Can you please review the changes?

### CODE REVIEW

**Comment by ltfish** [comment]
Thanks for this PR!

- `cfg_base.py`: It was a legit bug due to a typo.
- `cfg_accurate.py`: It was a bug caused by not updating the code after refactoring `Path`.
- `ddg.py`: I think you should use `self.kb.functions` instead, not `self.project.kb.functions`.

**Comment by axt** [comment]
Added a fix for it. Should I squash those two commits?

**Comment by ltfish** [comment]
I think you may squash the two commits regarding `ddg.py` to make history look cleaner.

**Comment by axt** [comment]
Ok! Done! Just wasnt sure if forced push interferes with pull-request. But it seems okay.

**Comment by ltfish** [comment]
Great. Thank you!

**Pull request merged**
