### PR TITLE
Update symbolic.rst with more information and example

### PR DESCRIPTION
**Pull request by Archfx**
This commit adds more information to the symbolic execution core-concepts page with a small example.

### CODE REVIEW

**Comment by twizmwazin** [comment]
Can you add newlines to keep the line lengths consistent with the rest of the file? I think the limit is 80 chars in the docs.

**Comment by Archfx** [comment]
> Can you add newlines to keep the line lengths consistent with the rest of the file? I think the limit is 80 chars in the docs.

Sure, let me update

**Comment by twizmwazin** [comment]
@rhelmot or @ltfish could one of you review this and merge it if you agree, or provide feedback if you don't?

**Comment by rhelmot** [comment]
Thanks for the contribution!

**Pull request merged**
