### PR TITLE
flake8 finds 13 undefined names

### PR DESCRIPTION
**Pull request by cclauss**
flake8 testing of https://github.com/angr/angr on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./angr/analyses/datagraph_meta.py:26:15: F821 undefined name 'DataGraphError'
        raise DataGraphError("No VFG node at 0x%x" % addr)
              ^
./angr/analyses/datagraph_meta.py:31:19: F821 undefined name 'DataGraphError'
            raise DataGraphError("No VFG node at this address")
                  ^
./angr/analyses/datagraph_meta.py:96:15: F821 undefined name 'DataGraphError'
        raise DataGraphError("Not Implemented")
              ^
./angr/analyses/girlscout.py:64:26: F821 undefined name 'SegmentList'
        self._seg_list = SegmentList()
                         ^
./angr/analyses/girlscout.py:198:28: F821 undefined name 'SimIRSB'
        if isinstance(run, SimIRSB):
                           ^
./angr/analyses/girlscout.py:324:27: F821 undefined name 'SimIRSB'
        if type(s_run) is SimIRSB:
                          ^
./angr/analyses/girlscout.py:336:30: F821 undefined name 'SimIRSB'
        if isinstance(s_run, SimIRSB):
                             ^
./angr/analyses/cfg/indirect_jump_resolvers/resolver.py:56:20: F821 undefined name 'SimMemoryError'
            except SimMemoryError:
                   ^
./angr/procedures/linux_loader/__tls_get_addr.py:8:19: F821 undefined name 'SimValueError'
            raise SimValueError("__tls_get_addr called with symbolic module ID")
                  ^
./angr/storage/paged_memory.py:239:21: F821 undefined name 'items'
                    items.insert(0, key)
                    ^
./tests/broken_FindAvoidConflict.py:29:20: F821 undefined name 'AngrError'
            except AngrError:
                   ^
./tests/test_file_struct_funcs.py:42:5: F821 undefined name 'run_test_file_struct_funcs'
    run_test_file_struct_funcs()
    ^
./tests/test_signed_div.py:28:5: F821 undefined name 'run_signed_div'
    run_signed_div()
    ^
13    F821 undefined name 'SimMemoryError'
13
```

### CODE REVIEW

**Comment by rhelmot** [comment]
On one hand, thanks, some of those bugs are real even though a bunch of them are in bitrotted and unused code, but on the other hand, just arbitrarily running a static analysis tool on a project and submitting the tools to run it constantly strikes me as... kind of rude? We already have a linter as part of this project's CI, thank you. It just works on an differential basis (your PR must not cause regressions over master) since this project is gigantic and lived for a very long time before being introduced to any software development practices whatsoever.

I'm going to close this and open an issue with the errors that aren't in unused modules.

**Comment by cclauss** [comment]
Sorry.   No intention to be rude.  Was just trying to help.

**Comment by cclauss** [comment]
You are right.  The other linters do not find undefined names.

**Comment by rhelmot** [comment]
We use pylint, [with these settings](https://github.com/angr/angr-dev/blob/master/pylintrc) which definitely does detect undefined names.

**Pull request closed without merging**
