### PR TITLE
Remove redundant Explorer attribute

### PR DESCRIPTION
**Pull request by tyb0807**
@rhelmot @ltfish please review this. Thanks!

### CODE REVIEW

**Comment by ltfish** [comment]
Looks good to me.

**Comment by ltfish** [comment]
@rhelmot ?

**Comment by tyb0807** [comment]
```
LINT FAILURE: angr/exploration_techniques/explorer.py regressed to 9.79/9.80
... W: 95, 4: Parameters differ from overridden 'setup' method (arguments-differ)
... W:137, 4: Parameters differ from overridden 'complete' method (arguments-differ)
```
Actually I don't know what does this Lint failure mean? Is it harmful?

**Comment by ltfish** [comment]
I think you can just rename the `pg` to `simgr`... Pylint is really strict.

**Comment by ltfish** [comment]
Thanks!

**Pull request merged**
