### PR TITLE
Fix BVS size None in SimMemory.store

### PR DESCRIPTION
**Pull request by tyb0807**
This was meant to be angr/simuvex#141, but it was forgotten for a while.

Thanks @ltfish

### CODE REVIEW

**Comment by ltfish** [comment]
```

**Comment by ltfish** [comment]
```
         if type(size_e) in (int, long): 
             size_e = self.state.se.BVV(size_e, self.state.arch.bits) 

+        if size_e is None: 
+            size_e = data_e.size() / 8 
+ 
```

I think the newly added `if ...` should go before the other `if ...` above it.

**Comment by tyb0807** [comment]
Yeah, I think the correct solution is the latter. Thanks @ltfish

**Comment by ltfish** [comment]
Thank you!

**Pull request merged**
