### PR TITLE
Fix some decompiler issues

### PR DESCRIPTION
**Pull request by DennyDai**
### fix if-then-else structures ec8b5ed
before:
`<Bool LShR(ailexpr_Conv(8->32, <BV8 ailtmp_197_20_8>) << 0x1c, 0x1e) != 0x0>`
`<Bool LShR(ailexpr_Conv(8->32, <BV8 ailtmp_197_19_8>) << 0x1c, 0x1e) == 0x0>`
```c
if ((int)None << 28 >> 30 != 0)
{
    // if statements
    goto 134218717;
}
if ((int)None << 28 >> 30 == 0)
{
    // else statements
}
// addr: 134218717
```
after:
`<Bool LShR(ailexpr_Conv(8->32, <BV8 ailtmp_197>) << 0x1c, 0x1e) != 0x0>`
`<Bool LShR(ailexpr_Conv(8->32, <BV8 ailtmp_197>) << 0x1c, 0x1e) == 0x0>`

```c
if ((int)None << 28 >> 30 != 0)
{
    // if statements
}
else
{
    // else statements
}
```
---
### remove function args from local variable declarations 29afc7d
before:
```c
void function_name(char[5]* a0, struct struct_0* a1) {
    char[5]* a0;
    struct struct_0* a1;
    unsigned int ir_0;
    unsigned int ir_1;
    unsigned int ir_2;
    // statements
}
```
after:
```c
void function_name(char[5]* a0, struct struct_0* a1) {
    unsigned int ir_0;
    unsigned int ir_1;
    unsigned int ir_2;
    // statements
}
```
---
### fix 'None' varibles in function body e1816f6
before:
```c
void function_name(char[5]* a0, struct struct_0* a1) {
    BOT <tmp 197>;
    BOT <tmp 12>;
    // more declarations..

    None = a0[4];
    None = (int)a0[4] << 28;
    // more statements...
}
```
after:
```c
void function_name(char[5]* a0, struct struct_0* a1) {
    BOT <tmp 197>;
    BOT <tmp 12>;
    // more declarations..

    <tmp 197> = a0[4];
    <tmp 12> = (int)a0[4] << 28;
    // more statements...
}
```
---
### fix operation precedence issue by adding parentheses e1a314d
before:
```c
if (ir_0 << 8 + ir_2 << 16 >> 16 > 0)
```
after:
```c
if ((((((ir_0 << 8) + ir_2) << 16 ) >> 16) > 0))
```
they are different because "+" has higher priority over "<<".

### CODE REVIEW

**Comment by ltfish** [comment]
Awesome job! Can you please fix the failing test case?

**Comment by DennyDai** [comment]
fixed :)

**Comment by ltfish** [comment]
@DennyDai the extra parentheses can be annoying to users if we are forcing `a = b + 1` to be displayed as `a = (b + 1)`. Do you want to look into how to get rid of unnecessary parentheses? I can merge all other commits if you revert `e1a314d` and `7ac8c60` for now.

**Comment by DennyDai** [comment]
Yes that's annoying not only for the case `a = (b + 1)`, but also for cases like `if ((a == b))`. That's more like a temporary solution to make sure it's correct. I'm not sure how to improve it for now. I've revert the commits and I will look into it later.

**Comment by ltfish** [comment]
> I'm not sure how to improve it for now.

There is an algorithm that will remove redundant parentheses. Some Googling directed me to [this](https://stackoverflow.com/questions/18400741/remove-redundant-parentheses-from-an-arithmetic-expression). Let me know if you want to give it a try, or I will implement it by myself!

**Comment by ltfish** [comment]
Merged. Thanks!

**Comment by DennyDai** [comment]
Thank you! and yes I can try to implement this.

**Pull request merged**
