### PR TITLE
fix Function.dbg_draw

### PR DESCRIPTION
**Pull request by ocean1**
pinned networkx version to 1.11
added pygraphviz to requirements

fixed import of graphviz_layout

### CODE REVIEW

**Comment by zardus** [comment]
Do the networkx requirements have to be `networkx==1.11`? That'll lock it at exactly 1.11. Maybe we should have `networkx>=1.11`?

I'm also not a fan of requiring pygraphviz. IIRC, that pulls in a *lot* of other requirements, and is the reason why we kept it out. I could be wrong; maybe @ltfish remembers.

**Comment by ltfish** [comment]
Let's remove pygraphviz from dependencies, and wrap `import pygraphviz` with `try... except...`. Installing libgraphviz and pygraphviz is not fun.

**Comment by zardus** [comment]
Ping, @ocean1

**Comment by zardus** [comment]
Actually, I went ahead and made the update to the requirements to speed up the process.

**Comment by ocean1** [comment]
sorry I did miss this notification!

**Pull request merged**
