### PR TITLE
Procedure setbuf

### PR DESCRIPTION
**Pull request by bannsec**
Because somehow this wasn't made already.

### CODE REVIEW

**Comment by ltfish** [comment]
I bet this will not pass linting...

**Comment by bannsec** [comment]
Gah,  Needs two spaces at top?

**Comment by ltfish** [comment]
`# pylint:disable=xxx`

Don't worry, the CI will complain :)

**Comment by bannsec** [comment]
removed the args so that the linter was happy and it broke it apparently >_<

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
