### PR TITLE
Add test_rol.py

### PR DESCRIPTION
**Pull request by extremecoders-re**
This PR adds test_rol.py

### CODE REVIEW

**Comment by zardus** [comment]
It looks like this PR is failing the builds :-(. `p` should be `proj` in the testcases, I guess? Could you fix that? If not, I can also do it. Let me know!

**Comment by extremecoders-re** [comment]
My bad :-(. 
It should be proj instead of p.

**Comment by zardus** [comment]
Almost there!

The way that `nosetests`, which we use for testing, works is that it runs all the methods that are prepended with `test_`. Would you mind changing `run_all` back to `test_all`.

Finally, @ronnychevalier feels very strongly that every commit to should pass CI, to make `git bisect` easier to use. Would you mind squashing all the commits into one?

Sorry to keep this back-and-forth going; I just don't want @ronnychevalier to tell me off again :-)

**Comment by extremecoders-re** [comment]
It is already `test_all`

Do you mean change from this 

```python
def test_all():
    test_rol_x86_64()
    test_rol_i386()

if __name__ == "__main__":
    test_all()
```
TO

```python
def test_all():
    test_rol_x86_64()
    test_rol_i386()

if __name__ == "__main__":
    run_all()
```

and yes, I would squash those commits.

**Comment by zardus** [comment]
Well, this ended up getting merged, un-squashed, because we decided to shoot from the hip and used it to test some code that runs github CIs through our internal PRs.

Thanks for the contribution!

**Pull request merged**
