### PR TITLE
ReachingDefinitionsAnalysis: extract data model

### PR DESCRIPTION
**Pull request by Pamplemousse**
300+ lines not related to the logic of the analysis could be moved into
their own file.

### CODE REVIEW

**Comment by rhelmot** [comment]
Fix CI (lint and api docs) and I will merge this.

**Comment by rhelmot** [comment]
jsyk, it's kind of hard to work with when you keep force-pushing like that. You can just keep pushing normal commits and I can hit the squash and merge button at the end.

**Comment by Pamplemousse** [comment]
True, although, it allows to keep a clean overall history, without squashing all commits together (esp. problematic on big PRs).

**Comment by Pamplemousse** [comment]
Thanks for merging!

**Pull request merged**
