### PR TITLE
fix filename handling in SimConcreteFilesystem

### PR DESCRIPTION
**Pull request by Kyle-Kyle**
There is a missing leading "/" which caused a lot of trouble

### CODE REVIEW

**Comment by rhelmot** [comment]
I don't think this is right, or if it is, then there's other problems. Look at this behavior of os.path.join:

```
In [2]: os.path.join('a', '/b')                                             
Out[2]: '/b'
```

Adding a leading slash to the guest path, which we will then join with the host path, will lead to a sandbox escape.

**Comment by Kyle-Kyle** [comment]
So what's the desired behavior? I thought spinning up `LocalTarget`means we also control the whole local machine?

**Comment by Kyle-Kyle** [comment]
But current implementation is definitely wrong. It can't find `./file`(In `LocalTarget`, this will be resolved to something does not exist) nor `/tmp/file`

**Comment by Kyle-Kyle** [comment]
OK. I get it. This conflicts the `chroot` behavior that we also need to support. Right?

**Comment by rhelmot** [comment]
Okay, I looked at it more carefully, and this is a good change but we also need to add some code to SimHostFilesystem._load_file to lstrip any leading slashes off the path before we join it to the host path.

**Comment by rhelmot** [comment]
yes, lol

**Pull request merged**
