### PR TITLE
added option to copy states when copy simgr

### PR DESCRIPTION
**Pull request by badnack**
Added option to copy states when copying a sim manager object

### CODE REVIEW

**Comment by rhelmot** [comment]
Can you explain what this fixes? States are meant to be immutable outside the context of an active step of execution, and even then a state will be copied first before it is mutated, eve.

**Comment by badnack** [comment]
Consider this snippet of code:

> simgr_copy = simgr.copy()
simgr_copy.active[0].memory.load(/* some_val */)
simgr_copy2 = simgr.copy()

Here simgr_copy2.active[0] might not equal to simgr.active[0]. The load performed by simgr_copy might have changed some data shared between the three above simgr objects. 

I had indeed the following problem today:

> simgr_copy = simgr.copy()
simgr_copy.active[0].memory.load(/* some_val */)
simgr_copy2 = simgr.copy()
simgr_copy2.step()

 here the step() was giving me back a pruned state. After removing the simgr_copy.active[0].load, I got an active state, though.

**Comment by rhelmot** [comment]
I would much rather this be solved by adding an option to the copy method itself, like `SimulationManager.copy(copy_states=True)` or something. This logic doesn't need to be invoked for every single copy operation, just the ones where you're sticking your fingers into the states.

**Comment by badnack** [comment]
well sure, that seems more elegant. Shall I close this merge request and open another one?

**Comment by rhelmot** [comment]
:+1:

**Comment by rhelmot** [comment]
Add a docstring for the `copy` function and I'll merge this.

**Comment by badnack** [comment]
docstrings are missing everywhere, I am just gonna add the one for the copy.

**Pull request closed without merging**
