### PR TITLE
I add a procedure in c standard lib

### PR DESCRIPTION
**Pull request by zd99921**
strncat with great help by strncpy,strlen

### CODE REVIEW

**Comment by rhelmot** [comment]
I don't think this is a correct implementation - shouldn't the limit passed to strncpy be limit - dst_len?

**Comment by rhelmot** [comment]
Also, remove the trailing newlines, they're failing lint

**Comment by zd99921** [comment]
I am not quite sure about the meaning of limit-dst_len, can you describe it in detail

**Comment by zd99921** [comment]
> I don't think this is a correct implementation - shouldn't the limit passed to strncpy be limit - dst_len?

I am not quite sure about the meaning of limit-dst_len, can you describe it in detail

**Comment by zd99921** [comment]
> I don't think this is a correct implementation - shouldn't the limit passed to strncpy be limit - dst_len?

The limit passed to strncpy is the number of characters added to the string dst, I don't think it needs -dst_len

**Comment by rhelmot** [comment]
I see, I had too much faith in the libc specification. This is correct, but it's still failing lint because now you don't have a newline at the end of your last line - every line is supposed to be terminated by a newline.

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
