### PR TITLE
Minor fixes and consistence enhancements

### PR DESCRIPTION
**Pull request by P1kachu**

### CODE REVIEW

**Comment by rhelmot** [comment]
These changes are good! Can someone in front of a computer please merge them?

**Comment by zardus** [comment]
@P1kachu, would you mind rebasing the changes on the current master to eliminate that merge commits? Those merge conflict resolution commits make replaying history a nightmare, and we have enough in-progress dev branches at the moment that it'll put a serious hamper on things.

Other than that, thanks!

**Comment by P1kachu** [comment]
Yep I'll check that

**Comment by P1kachu** [comment]
Done !

**Pull request merged**
