### PR TITLE
Added 'recursion depth limit error' failing binary

### PR DESCRIPTION
**Pull request by riyadparvez**
From discussion: https://github.com/angr/angr/issues/28

### CODE REVIEW

**Comment by zardus** [comment]
Could you also add a testcase (see the format in the other `test_*.py` files) that triggers this bug?

**Comment by riyadparvez** [comment]
I don't have any experience with nose. I did my best. Please have a look.

**Comment by zardus** [comment]
Not too bad :-)

nose is pretty nice; technically, that testcase could be one or two lines. If the function excepts out, then the testcase is counted as failed. Otherwise, it's considered as passed.

Both @ltfish and I are in the middle of some invasive refactoring, but we'll try to get to this as soon as we can!

**Comment by ltfish** [comment]
@zardus should we move this binary to the public `binaries` repo?

**Comment by zardus** [comment]
Yep! Could you do it, and then merge this pr?

And then, of course, fix the bug ;-)

**Comment by zardus** [comment]
In the year since this issue was open, the VFG was probably rewritten about two times. I'm going to close this to clean up the PR list, on the assumption that one of those rewrites fixed it.

**Pull request closed without merging**
