### PR TITLE
Riscv dev

### PR DESCRIPTION
**Pull request by mbrattain**

### CODE REVIEW

**Comment by rhelmot** [comment]
Assigning fish because of all the changes to the jumptable resolver and the light engine

**Comment by rhelmot** [comment]
Oh, I see, you accidentally included the changes from https://github.com/angr/angr/pull/2275 in this PR. could you snip that commit out of this PR?

**Comment by mbrattain** [comment]
@rhelmot My bad!

**Comment by rhelmot** [comment]
thanks!

**Pull request merged**
