### PR TITLE
Added ipdb as requirement

### PR DESCRIPTION
**Pull request by riyadparvez**

### CODE REVIEW

**Comment by ltfish** [comment]
Why is `ipdb` required?

**Comment by riyadparvez** [comment]
These are the lines where `ipdb` has been used: https://github.com/angr/angr/search?utf8=%E2%9C%93&q=ipdb

**Comment by ltfish** [comment]
lol they should all be removed. We use ipdb as a debugger and what you see in the code are breakpoints someone set earlier. They shouldn't exist in the code. And of course, angr does not require ipdb to run normally.

**Comment by riyadparvez** [comment]
Thanks for the clarification. You can close the PR if you want.

**Pull request closed without merging**
