### PR TITLE
Update Readme CI badge to github actions

### PR DESCRIPTION
**Pull request by twizmwazin**

### CODE REVIEW

**Comment by mborgerson** [comment]
How do you feel about just removing the badge, since GitHub already shows CI status at the top of the page

**Comment by ltfish** [comment]
+1 - maybe we don't need the badge on the GitHub readme page. We can add this badge to angr.io if you want.

**Comment by rhelmot** [comment]
-1 - the readme shows up as the landing page on the [pypi project](https://pypi.org/project/angr/), and we want the badge to show up there.

**Comment by mborgerson** [comment]
Why do we want the badge to show up on the PyPI page? The CI badge is for the master branch CI status, but the pypi project shows the readme text for whatever release version was published. Whatever the CI status is, it becomes irrelevant on PyPI once master branch advances beyond the released version on PyPI

**Pull request merged**
