### PR TITLE
add typehint for known plugins in AnalysesHub

### PR DESCRIPTION
**Pull request by syheliel**
Previously, if you are trying to use proj.analyses.CFG, there are no IDE support for class definition. This PR using `typing.Protocol` to add the existing analyses plugin into AnalysesHub. Now IDE can read the parameter when using plguin like `proj.analyses.CFGEmulated`
image

### CODE REVIEW

**Comment by rhelmot** [comment]
I think a better approach than this would be to make that type the type of the analyses member of Project instead of making that a subclass of AnalysisHub. However I am going to defer to @fmagin on this matter :)

**Comment by rhelmot** [comment]
Context: https://github.com/angr/angr/pull/3053

**Comment by syheliel** [comment]
Now I create a new class `AnalysesHubWithDefault` to cover my modfication.

**Comment by fmagin** [comment]
But now `project.analyses` is only annotated as `AnalysisesHubWithDefault`, which misses the methods of `AnalysesHub`, because `AnalysesHubWithDefault` only inherits from `PluginVendor` and `KnownAnalysesPlugin`? I think it should be:
`class AnalysesHubWithDefault(AnalysesHub, KnownAnalysesPlugin):` instead?

**Comment by ltfish** [comment]
Does this PR deprecate #3053?

**Comment by fmagin** [comment]
> Does this PR deprecate #3053?

No! The feature of #3053 allows _any_ analysis to be used in a way that is compatible with IDEs and type checking and doesn't even require registering the analysis first.
The PR discussed here only adds type hints for the analyses that are registered by default, and not for any analysis that might be defined as part of another codebase that uses angr.

**Comment by syheliel** [comment]
> test_rex.test_linux_network_stacksmash_64 ... ERROR

The CI fails in https://github.com/angr/angr/actions/runs/4695141037/jobs/8324122729, I can't find the test code in angr repo. Is this fail related to my code?

**Comment by ltfish** [comment]
It is a flaky test case that has nothing to do with your code.

**Comment by ltfish** [comment]
@rhelmot Can you merge it if it looks ok to you?

**Review by rhelmot — APPROVED** [review]

**Comment by rhelmot** [comment]
Thank you!

**Pull request merged**
