### PR TITLE
improve ultra page speed

### PR DESCRIPTION
**Pull request by salls**
1. grab concrete vals as bytes in one go rather than integers with shifting in a loop.
2. find the next symbolic object rather than repeatedly checking what symbolic object would be at each address

### CODE REVIEW

**Comment by salls** [comment]
not surprised, I'll investigate this more

**Comment by salls** [comment]
old:
```
s.regs.rax = s.solver.BVS("A",64)
%timeit s.regs.rax
> 28.6 µs ± 264 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
s.regs.rax = 1
%timeit s.regs.rax
> 25.4 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

new
```
s.regs.rax = s.solver.BVS("A",64)
%timeit s.regs.rax
> 24.6 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
s.regs.rax = 1
%timeit s.regs.rax
> 24.8 µs ± 56.4 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```


old
-----------
```
angr/tests/storage/test_memory_merge.py
0m1.238s

angr/tests/procedures/libc/test_string.py
1m3.402s

angr/tests/storage/test_memory.py
0m19.674s
```

new
-----------
```
angr/tests/storage/test_memory_merge.py
0m0.956s

angr/tests/procedures/libc/test_string.py
0m23.164s

angr/tests/storage/test_memory.py
0m5.979s
```

**Comment by salls** [comment]
Okay now it's good and it even passes the lint test

**Comment by ltfish** [comment]
I think this PR drops support for bytes that are not 8-bit long.

**Comment by zardus** [comment]
IMO, given the crazy speed boost here, we should probably:

a) For now, drop this part of the differently-sized byte support
b) If we want it going forward, make two subclasses of UltraPage: this normal fast one, and one that supports differently-sized bits

**Comment by rhelmot** [comment]
I would support dropping that support and leaving this PR as a signpost for anyone who actually wants it to work ever again.

**Comment by salls** [comment]
Given that .concrete_data is a ByteArray I assumed non 8-bit bytes were already broken. But maybe there's some magic I was missing out on? 
If someone wants support for that, one option would be a separate memory class where the speed hit is accepted?

**Comment by salls** [comment]
Was the only non 8 bit byte architecture clemency? haha

**Comment by rhelmot** [comment]
Clemency and another CTF arch CT64 from angr-platforms

**Comment by ltfish** [comment]
I'm fine with UltraPage only supporting 8-bit bytes moving forward.

**Comment by ltfish** [comment]
Thank you @salls!

**Pull request merged**
