### PR TITLE
lazy fix for lazy solves?

### PR DESCRIPTION
**Pull request by r00tus3r**

### CODE REVIEW

**Comment by mahaloz** [comment]
But was it done lazily?

**Comment by r00tus3r** [comment]
Of course!

@ltfish please review.

**Comment by ltfish** [comment]
@zardus @rhelmot I made this fix (on r00tus3r's laptop). Do any of you still remember this logic well enough to check it?

**Review by rhelmot — APPROVED** [review]
yeah that's fine

**Pull request merged**
