### PR TITLE
Use str.format() instead of "%X" % (args) in engines/successors.py

### PR DESCRIPTION
**Pull request by aflorea-2k**
Currently, engines/successors.py is using the percentage-style string format (which looks like this: `"%d" % (17)`).

This commit changes that.

The reason being, I am testing some analysis on angr, and I want to return some types which are different from the ones angr is expecting. Everything works, apart from SimSuccessors.\_\_repr\_\_, which because of the percentage-style formats is very strict.

### CODE REVIEW

**Comment by rhelmot** [comment]
Two things - 

1) we generally prefer formatting with f-strings as our replacement for %-formatting.
2) could a formatting specifier like :#x replace the explicit call to hex()?

**Comment by aflorea-2k** [comment]
Ok, I'm looking into using f-strings instead.

As for removing the hex call; I feel that
```
if isinstance(self.addr, int):
    return f'<{self.descritption} from {self.addr:#x}: {result}>'
else:
    return f'<{self.descritption} from {self.addr}: {result}>'
```
would be a pretty roundabout way of doing it.. Sadly I'm not knowledgeable enough of Python to come up  with some other way..

**Comment by rhelmot** [comment]
I see. I mistakenly thought that the format code would be ignored if it were inapplicable. Your solution is fine then.

**Comment by rhelmot** [comment]
I'm not sure why CI hasn't picked this one up, but it seems benign enough that I'm just going to merge it.

**Comment by ltfish** [comment]
Umm `addr_display` is undefined...

**Pull request merged**
