### PR TITLE
Add Decompiler Corpus Test Framework

### PR DESCRIPTION
**Pull request by erhlee-bird**
This pull request introduces a test framework specifically meant to exercise angr's decompilation capabilities. It is intended to validate that angr is able to successfully analyze and decompile known files from a test corpus, as well as produce deterministic decompilation output.

The changes are isolated to a couple new GitHub Actions workflows and scripts provided under `corpus_tests/`.

Below are links to the submitted README files from this PR as well as example setups of the recommended additional supporting repositories.

- https://github.com/project-purcellville/angr/blob/master/corpus_tests/README.md
- https://github.com/project-purcellville/snapshots-0000/blob/main/README.md
- https://github.com/project-purcellville/direct-file-store-0000

### CODE REVIEW

**Comment by rhelmot** [comment]
lgtm as a concept, but we will need a) CI to pass before we hit merge and b) we either need admin on the project-purcellville namespace or we need to move the aux repos to the angr namespace.

**Comment by erhlee-bird** [comment]
@rhelmot, I've added the three of you as owners of the organization. We can proceed at your discretion in dealing with the aux repos.

I'm working on the failing CI checks but will note that the passing of the newly added check introduced by this PR will depend on the aux repos being in place.

**Comment by erhlee-bird** [comment]
Okay, the PR is ready for the aux repos to be moved.
I'll update all references to project-purcellville to angr and point to documentation for what secrets need to be prepared in the repository.

**Comment by ltfish** [comment]
@erhlee-bird Can you please assign me proper permissions to your organization?

**Comment by erhlee-bird** [comment]
@ltfish I just resent the invite to you

**Comment by ltfish** [comment]
I'm merging this PR and will fix failing things on angr master, given how difficult it is to test the workflow on PRs.

**Pull request merged**
