### PR TITLE
Correct type error in `angr/calling_conventions.py`

### PR DESCRIPTION
**Pull request by Pamplemousse**
Signed-off-by: Pamplemousse <xav.maso@gmail.com>

### CODE REVIEW

**Comment by rhelmot** [comment]
Saying it's a `SimCC` implies it's an instance of a SimCC; `type` is more correct. Even more correct would be something like `typeof[SimCC]` (I forget the syntax exactly).

**Comment by Pamplemousse** [comment]
Oh, good catch!
Did not realise as my consumer code was only calling the "static" parts of `SimCC`...
See https://mypy.readthedocs.io/en/stable/kinds_of_types.html#the-type-of-class-objects for the syntax.

**Comment by ltfish** [comment]
Did mypy catch this? It wasn't incorrect before.

**Comment by Pamplemousse** [comment]
@ltfish it caught this on some code I have, getting something from the `DEFAULT_CC`, and trying to access `ARG_REGS` on the result...

Depending on what you ran `mypy` on, the previous annotation might not be wrong (over-approximated).

**Pull request merged**
