### PR TITLE
Added a text editor.

### PR DESCRIPTION
**Pull request by chadbrewbaker**
I found the Docker container really hard to work in without a text editor.

### CODE REVIEW

**Comment by zardus** [comment]
I forgot we had a Dockerfile in this repo... The "real" dockerfile is in https://github.com/angr/angr-dev. This PR should go there, and we should probably get rid of this dockerfile.

Whether we want to have an editor in the default angr dockerfile is another question. Vim's probably ok, though :-)

**Comment by ltfish** [comment]
Just saying, I'm good as long as it's not Emacs.

**Comment by rhelmot** [comment]
This dockerfile is important because this is the one that `docker pull angr/angr` ends up retrieving, I think. There's... some CI somewhere that automatically builds this one.

**Comment by zardus** [comment]
I set up the `angr/angr` docker hub image to auto-build from angr-dev, actually. Any push to master on any angr repository triggers it, but it grabs angr-dev for sure. Had to manually mess with URL parameters on docker hub to create it that way :-)

**Comment by zardus** [comment]
Closing this, since we got the other one :-)

**Pull request closed without merging**
