### PR TITLE
Handle SimUnion in refine_locs_with_struct_type by treating it as its largest member

### PR DESCRIPTION
**Pull request by AlLongley**
Fixes `TypeError: I don't know how to lay out a union None` when executing/parsing a SimUnion passed directly as a SimProcedure argument, typical of Windows ws2_32.dlls deprecated `inet_ntoa`

Raised in Issue https://github.com/angr/angr/issues/3496

### CODE REVIEW

**Comment by rhelmot** [comment]
Please fix linting and I'll hit merge!

**Comment by rhelmot** [comment]
uh, I'm not super sure that those were the right changes to make. You shouldn't have to change any files that you didn't originally touch...

**Comment by AlLongley** [comment]
Wrong branch, my apologies. The world is not ready for that yet

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
