### PR TITLE
Complete fix for GirlScout

### PR DESCRIPTION
**Pull request by pietrodn**
This PR fixes all the problems that make `girlscout.py` crash.

It solves issue #447 and supersedes PRs #248, #301, #313 fixing the same problems and an additional one which is described in the issue.

### CODE REVIEW

**Comment by ltfish** [comment]
If it works now with your commits, I'm happy to take in this PR! Thanks!

I won't have time to test it before next Monday. If you can write a test case or re-enable existing "broken" GirlScout test cases, I'll merge it in as soon as it passes on Travis CI.

**Comment by pietrodn** [comment]
Well, it works in the sense that girlscout no longer crashes when I execute it, but it is still not able to determine the base address of any binary, because it does not detect any indirect jump. I guess that it will need further work.

**Comment by ltfish** [comment]
That's also my feeling. In fact I'm planning to rewrite it on top of CFGFast.

**Comment by pietrodn** [comment]
I'm currently working on it, I've done other fixes and now it's able to detect functions (but not the base address yet).

**Pull request closed without merging**
