### PR TITLE
Better handling of mips branching - fixes issue that came up in Issue #1045

### PR DESCRIPTION
**Pull request by Kingloko**

### CODE REVIEW

**Comment by rhelmot** [comment]
Looks good to me, with the exception that you seem to have mixed tabs and spaces? Fix that and I'll merge it.

**Comment by ltfish** [comment]
How did it pass our linting...

**Comment by Kingloko** [comment]
I assumed there was a vimrc on the docker container that took care of that for me. My bad. Would a PR to angr-dev with a default vimrc and an `echo vimrc >> /home/angr/.vimrc` at the end of the Dockerfile be something you're interested in?

**Comment by rhelmot** [comment]
Yeah, that would be a good PR :)

**Pull request merged**
