### PR TITLE
Move graph-related algorithms to utils/graph.py

### PR DESCRIPTION
**Pull request by ltfish**

### CODE REVIEW

**Comment by rhelmot** [comment]
I would prefer these went in angr.graph_utils or similar. angr.misc is currently only for things related to the management of python code itself.

**Comment by ltfish** [comment]
How about an `angr.utils` package?

**Comment by rhelmot** [comment]
Fine by me. what else do you want to put there?

**Comment by ltfish** [comment]
All sorts of algorithms that we end up implementing by ourselves?

**Pull request merged**
