### PR TITLE
CFG indirect jump resolution refactor

### PR DESCRIPTION
**Pull request by tyb0807**
@ltfish Please check this out. First TODO of the series in #1063

### CODE REVIEW

**Comment by ltfish** [comment]
Linting failed. Please fix :)

**Comment by tyb0807** [comment]
Now we have to merge shellphish/fuzzer#28 first

**Comment by ltfish** [comment]
Actually, this is a good time to unify the naming of options. I've been mocked multiple times by @zardus that my option names are terrible -- they are all too long. As a start, we can remove all the `enable_` prefixes so they are shorter and more precise. What do you think?

**Comment by ltfish** [comment]
You also don't want to just remove the old options. Since it's a public interface, we should still accept values from old options, with a deprecation warning printed out. We can remove the options after several months (I would say 3 since 3 is magical ;) ).

**Comment by tyb0807** [comment]
@ltfish Is it ok now?

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
