### PR TITLE
Fix ret deduplicator on fake_return nodes

### PR DESCRIPTION
**Pull request by mahaloz**

### CODE REVIEW

**Comment by rhelmot** [comment]
zion do you maybe wanna `pip install pre-commit && pre-commit install`

**Comment by mahaloz** [comment]
> zion do you maybe wanna `pip install pre-commit && pre-commit install`

LOL. @rhelmot is it a problem having the CI do this much work? Cause if it is, I will do it; otherwise, I'd prefer to not have it

**Comment by rhelmot** [comment]
It's more for the sake of your own email inbox (and mine) not getting spammed

**Comment by mahaloz** [comment]
I don't want to do it :(, but I'll try having it on my system one more time because I rather not make all org owners mad.

**Pull request merged**
