### PR TITLE
Enforce correct endianness when using ConcreteTarget

### PR DESCRIPTION
**Pull request by degrigis**
Fix for https://github.com/angr/angr/issues/2579

### CODE REVIEW

**Comment by ltfish** [comment]
@rhelmot I feel this may cause issues for non-standard value reads... For example, if it asks for a default value of 100 bytes, do we really want to reverse the 800-bit BV?

**Comment by rhelmot** [comment]
Thought about this a bit more and I think the right thing to do is to reverse it based not on arch.endness but rather the endness of the current load. That should maybe be in kwargs? if not, you can add it being passed in?

**Comment by ltfish** [comment]
I agree with @rhelmot .

**Comment by ltfish** [comment]
> Just as a curiosity, why is this different than using the arch endness?

The read that triggers `_default_value()` may not be using the arch endness (in some weird memory loading statements).

**Pull request merged**
