### PR TITLE
ARM64 support in disassembly

### PR DESCRIPTION
**Pull request by xxr0ss**
Added aarch64-specific `disect_instruction_for_aarch64()` function. I think patching the existing `disect_instruction` can hardly help, instead it easily messes up the code.

Testcases are also added.

BTW, I have read some of the previous PRs and code in capstone-engine, I think condition code/shifter/extender should be treated as attributes of opcode/operands (at least for arm64).

And according to [wikipedia](https://en.wikipedia.org/wiki/Instruction_set_architecture):

> [Machine language](https://en.wikipedia.org/wiki/Machine_code) is built up from discrete statements or instructions. On the processing architecture, a given instruction may specify:
> - opcode (the instruction to be performed) e.g. add, copy, test
> - any explicit operands:
>   - [registers](https://en.wikipedia.org/wiki/Processor_register)
>   - literal/constant values
>   - [addressing modes](https://en.wikipedia.org/wiki/Addressing_mode) used to access memory

So I think it makes sense that capstone engine do not treat them as operands.

Also, let's just stop hackish workarounds and do different instruction disection for different architectures!

### CODE REVIEW

**Comment by xxr0ss** [comment]
**STATUS:** Fixing

Well, do not merge for now, I found new unhandled instruction. 😢

**Comment by rhelmot** [comment]
- is this ready to merge?
- are all the instructions you added edge case support for represented in the testcases?

**Comment by xxr0ss** [comment]
@rhelmot Yes, all edge cases have been added in the testcases.

**Comment by rhelmot** [comment]
Thank you!!

**Pull request merged**
