### PR TITLE
A couple more comments and reformatting.

### PR DESCRIPTION
**Pull request by ekse**
Please double-check the description of ErroredPath, the rest should be straightforward changes.

### CODE REVIEW

**Comment by rhelmot** [comment]
Can you remove the docstring on FunctionDict? That class is pretty janky and almost totally useless except for the one (private) usage of it in that file, and I don't think it should be in our docs.

**Comment by ekse** [comment]
I will update the commit tonight. An alternative would be to specify in the sphinx .rst files not to include this class in the documentation.

**Comment by zardus** [comment]
Doesn't the .rst update method sound better? It seems weird to explicitly suppress documentation. Just because it's not used publicly doesn't mean that we won't want to glance at the documentation in the file sometimes.

**Comment by ltfish** [comment]
I would vote for the .rst method. Personally I read those documentation for internal stuff quite often. Also documentation on internal data structures is useful for whoever ends up developing on angr.

**Comment by ekse** [comment]
I opened a pull request in angr-doc. Sphinx does not seem to have a an handy way to skip documenting some classes so I whitelisted FunctionManager instead.

https://github.com/angr/angr-doc/pull/40

**Comment by ltfish** [comment]
Can someone (like @zardus and @rhelmot) take the lead on this PR?

**Comment by zardus** [comment]
Sorry about the delayed merge. We've been traveling, and basically dumped the workload of 5 people on rhelmot :-)

**Pull request merged**
