### PR TITLE
RDA: Remove duplication in `engine_vex`

### PR DESCRIPTION
**Pull request by Pamplemousse**
... between `_handle_Store` and `_handle_StoreG`.
Make the second call the first.

### CODE REVIEW

**Comment by Pamplemousse** [comment]
Oh! I did not know you did such a refactor :)
Sounds very promising, I guess there will have to be a rewrite of the `engine_vex` and `engine_ail` in `RDA` to make use of this.

Is it production ready?
Is there any document/documentation about your work somewhere to catch up with the new SimEngine?
Any open issues, or planned tasks already determined following your work?

**Comment by rhelmot** [comment]
There is no real documentation for it yet, as I was going to wait until I was done with the ongoing SimMemory refactor. However, you can read the manifesto I wrote nearly a year ago about the overarching design philosophy I want to take forward with respect to angr's organization: [statecraft.txt](https://github.com/angr/angr/files/4517063/statecraft.txt). long story short I believe we can have engines made of modular components which implement generic and specific functionality that can be composed almost to the point of removing object-orientation from states.

Beyond that, [angr/engines/vex/light/light.py](https://github.com/angr/angr/blob/master/angr/engines/vex/light/light.py) should be fairly self-explanatory to read. The structure of the angr/engines/vex folder is that the light folder contains pieces and mixins which make very few assumptions about the structure of the state or the data domain, the claripy folder contains pieces which assumes the data domain is claripy ASTs, and the heavy folder contains pieces which assume the claripy domain and the SimState/SimStatePlugin architecture.

**Comment by ltfish** [comment]
@Pamplemousse Please do not change the interface for `_handle_Store()`. You can add a new method (e.g., `_handle_Store_core()`) if you want `_handle_Store()` and `_handle_StoreG()` to share code.

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
