### PR TITLE
add support for Iop_Dupxxx

### PR DESCRIPTION
**Pull request by Luluno01**
Support for vector duplication IR ops added along with some test cases.

### CODE REVIEW

**Comment by rhelmot** [comment]
lint failures:

```
LINT FAILURE: tests/test_vex.py regressed to 9.90/9.93
... tests/test_vex.py:259:4: W0621: Redefining name 'g' from outer scope (line 385) (redefined-outer-name)
... tests/test_vex.py:282:4: W0621: Redefining name 'l' from outer scope (line 11) (redefined-outer-name)
```

Additionally, it would be nice if we didn't have to add a special case to categorize the dup ops - I think if you name the method `_op_generic_Dup` and annotate it with `@supports_vector` it should be categorized automatically.

**Comment by rhelmot** [comment]
Oh, and yes you should use concat instead of shift-or to create the duplicated vectors.

**Comment by Luluno01** [comment]
@rhelmot So should I close and reopen a new PR fixing these?

**Comment by rhelmot** [comment]
No, you can push new changes to this branch and they will be reflected in the PR.

**Comment by Luluno01** [comment]
Okay, working on it

**Comment by Luluno01** [comment]
There are still two lint failures but they are not caused by my code. I am afraid there are some reasons for these codes to be committed without fixing the lint so I left them unchanged.

**Comment by Luluno01** [comment]
Wow I did not fix lint problems in codes not written by me and the lint check passed magically.

**Comment by rhelmot** [comment]
Looks good to me! Thanks so much!

**Comment by Luluno01** [comment]
Thank you! I now have to resolve the conflicts in another PR.

**Pull request merged**
