### PR TITLE
Add prototypes and MS 64-bit CC

### PR DESCRIPTION
**Pull request by schieb**
Prototypes for all kernel32 and advapi APIs were constructed using
@rhelmot's CalleeCleanupFinder analysis

### CODE REVIEW

**Comment by ltfish** [comment]
This PR reminds me of my commit (https://github.com/angr/angr/pull/811/commits/9c76a563bd7a07e80207b00a1feb2f0d0a07de7a). @rhelmot What do you think of merging my commit to master as well?

**Comment by rhelmot** [comment]
Also, you have a single lint failure left :sweat_smile:

**Comment by schieb** [comment]
Huh, that is weird. The lint of the first commit told me I needed to add a newline:

`LINT FAILURE: new file angr/procedures/win32/InterlockedExchange.py lints at 9.09/10.00. Errors:
... C: 18, 0: Final newline missing (missing-final-newline)`

**Comment by ltfish** [comment]
Merged. Thank you!

**Pull request merged**
