### PR TITLE
Some more docstrings reformatting.

### PR DESCRIPTION
**Pull request by ekse**
Mostly docstrings reformatting and adding files to the generated apidoc, fixed a couple typos.

### CODE REVIEW

**Comment by zardus** [comment]
We're trying to get one more refactor merged in, then we'll rebase this on the latest codebase, fix the conflicts, and merge it :-)

**Comment by ltfish** [comment]
I'm expecting to have a release in 24 hours (if everything works), and then we'll rebase your PR and merge it in!

**Comment by ltfish** [comment]
Apparently things didn't work well last Friday :-( but they seem to be working now. So a release is coming pretty soon!

**Comment by ltfish** [comment]
By the way, I have some questions: is the indent between `:param xxx:` and the actual description necessary? Is it just for better visual effects? Is there anyway to automatically indent the description in vim or PyCharm?

**Comment by ekse** [comment]
No problem, I will rebase and fix the conflicts. The indentation is optional, some of the docstrings were already indented and I think it makes it easier to read than without. I don't know about a way to automatically do the indentation.

**Comment by ltfish** [comment]
Thanks for rebasing the conflicts! We'll merge it in as soon as possible after seeing your new requests!

**Comment by ekse** [comment]
Rebased. I hope I did not mess anything up, the tests seem to be running fine. I reformatted 2 files that either had mixed tabs and spaces or very long lines.

**Comment by zardus** [comment]
Thanks! All the testcases passed on our side, too.

**Pull request merged**
