### PR TITLE
Adding Posix String Formatter

### PR DESCRIPTION
**Pull request by marcusbotacin**
Considering the cases where posix.dumps() returns a stream like "foo\x0000\bar\x0000\x7". Wouldn't be better to have an option to get ['foo','bar',7]? I implemented this feature via optional format parameter. It takes struct-like args (in this case 'ssi') and returns formatted parameters. As it is optional, it does not break current dumps operation.

### CODE REVIEW

**Comment by rhelmot** [comment]
Original comments from first PR still apply - this code would only work in extremely limited cases because of how you've placed it. Please make it work more consistently

**Comment by marcusbotacin** [comment]
I added the formatting capabilities to the other file descriptors, as suggested.

**Comment by marcusbotacin** [comment]
Idk what this failure message means, since I have not changed anything than adding an oprtional parameter.

**Comment by marcusbotacin** [comment]
I fixed all lint issues, now it is closer to what was expected.

**Comment by rhelmot** [comment]
I've been thinking, and I don't actually think i want to accept this change. This is a complicated feature that defines a custom format string protocol with limited applicability and high potential for things to go wrong. It's technical debt I don't want to take on.

Sorry for wasting your time.

**Pull request closed without merging**
