### PR TITLE
Implement knowledge base plugins subsystem

### PR DESCRIPTION
**Pull request by danse-macabre**
The following pull request introduces two major changes:

- KnowledgeBase is now a plugin-based entity. This would allow the extension of the knowledge base with a user-specific plugins without altering the actual angr codebase.

- The codenode.py and keyed_region.py modules were moved to a global scope, as there are also used outside the context of the KnowledgeBase and do not strictly fall into the category of knowledge base plugins.

### CODE REVIEW

**Comment by rhelmot** [comment]
This is great, thank you!

Can I ask what sort of work you're doing that prompted this change? If you're interested in doing more work on the knowledge base, we have a direction we've been trying to go in, that is, having the knowledge base be more of a database in the sense of having consistency checks and less duplicate data and allowing it to be easily serialized as a record of analysis, but we haven't had time to work toward this.

**Comment by danse-macabre** [comment]
@rhelmot Thank you for your response!

Right now I'm doing some heavy automated RE-analysis on a very diverse set of real-world binaries. Although the most of the analyses code is based on the angr framework, it introduces quite a lot of angr API and internal structure changes, which is difficult to maintain for those parts of angr, which aren't engaged in the analysis process. When the THE END TIMES *(c)* has come, it started to become more and more difficult to keep these changes intact. 

The following pull request, as well, as the others I'm planning to do, is dedicated to make the angr core more extensible, in order to allow one implement some new, very project-specific, features, without bringing a chaos upon the angr code base (thus, making the integration process much easier, than it is now). Hope, you will find them useful.

Unfortunately, I have no time to work on any changes that are not strictly related to my current work, so I will not be able to work in the direction you proposed.

Thanks again,
danse.

**Comment by ltfish** [comment]
> The following pull request, as well, as the others I'm planning to do, is dedicated to make the angr core more extensible, in order to allow one implement some new, very project-specific, features, without bringing a chaos upon the angr code base (thus, making the integration process much easier, than it is now). Hope, you will find them useful.

We will be very happy to take PRs on changes that make angr core more extensible. The more PRs you submit (and are accepted), the less maintaining you will have to do by yourself :-)

**Comment by ltfish** [comment]
The changes look good to me. @zardus @rhelmot Comments?

@danse-macabre Please rebase your changes on top of the latest master branch to fix the conflicts. Thanks! (I was the one pushing changes to master yesterday, so feel free to blame me!)

**Comment by zardus** [comment]
Yep, I agree with the plugin architecture. I also think this will give us
more flexibility in picking, saving and backtracking, and so on.

:+1:

On Aug 13, 2017 11:25 AM, "Fish" <notifications@github.com> wrote:

The changes look good to me. @zardus <https://github.com/zardus> @rhelmot
<https://github.com/rhelmot> Comments?

@danse-macabre <https://github.com/danse-macabre> Please rebase your
changes on top of the latest master branch to fix the conflicts. Thanks! (I
was the one pushing changes to master yesterday, so feel free to blame me!)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/angr/angr/pull/577#issuecomment-322058321>, or mute the
thread

**Comment by danse-macabre** [comment]
@ltfish 

Done. Seems like I messed something while doing a reset on github remote, but according to the commit history now everything is alright.

**Comment by ltfish** [comment]
Thanks!

**Pull request merged**
