### PR TITLE
Merge identifier into angr

### PR DESCRIPTION
**Pull request by CodeMaxx**
Refer to #494 for previous discussion

### CODE REVIEW

**Comment by CodeMaxx** [comment]
@ltfish Any idea why Travis didn't start on this one?

**Comment by ltfish** [comment]
Travis CI just started. It was busy I guess.

I strongly recommend you to use our internal CI, which is N times faster than Travis CI.

**Comment by CodeMaxx** [comment]
How do I use the internal CI?

**Comment by CodeMaxx** [comment]
So most of the Lint errors are due to unused variables. I think those are there due to some future expected functionality. Should I disable pylint on all those then?

**Comment by CodeMaxx** [comment]
Should work after merging https://github.com/shellphish/patcherex/pull/5

**Comment by zardus** [comment]
Okay! I went through it and I think it's ready to merge, especially so that we can get the CI working again. @salls, any last-minute objections?

**Comment by salls** [comment]
I still want the warning and I think we should rename custom_callable since it defines a class Callable and I don't want to use a name that exists elsewhere in angr

**Comment by CodeMaxx** [comment]
@salls Done

**Comment by zardus** [comment]
Amazing job!

**Pull request merged**
