### PR TITLE
Changing the order of the mixins for DeafaultListPagesMemory()

### PR DESCRIPTION
**Pull request by AOS002**
InspectMixinHigh has been moved after AddressConcretizationMixin, so that size is set before InspectMixinHigh.store() is called

### CODE REVIEW

**Comment by rhelmot** [comment]
this is a bad change - it is a desired feature that inspecting a symbolic memory read/write lets you capture the symbolic instead of the concretized address.

**Comment by AOS002** [comment]
> this is a bad change - it is a desired feature that inspecting a symbolic memory read/write lets you capture the symbolic instead of the concretized address.

But this happens even when the size is concrete not just symbolic

**Comment by rhelmot** [comment]
I'm talking about addresses, not sizes

**Comment by AOS002** [comment]
> I'm talking about addresses, not sizes

ohh I see, what if we move it after SizeNormalizationMixin instead

**Comment by rhelmot** [comment]
Sound good to me, assuming tests pass

**Pull request merged**
