### PR TITLE
Add X86PeIatResolver

### PR DESCRIPTION
**Pull request by schieb**
Resolve indirect calls through the IAT for X86 PE binaries

### CODE REVIEW

**Comment by ltfish** [comment]
Can you please add a test case for this resolver, so future changes to CFGFast do not accidentally break it?

**Comment by schieb** [comment]
Sure, I'll be able to get to that this weekend.

**Comment by ltfish** [comment]
Thanks!

**Comment by schieb** [comment]
@ltfish Added the test. I force pushed so not sure if you will be alerted automatically.

**Comment by ltfish** [comment]
> I force pushed so not sure if you will be alerted automatically.

I wasn't!

**Comment by ltfish** [comment]
Thanks!

**Pull request merged**
