### PR TITLE
add an angr/procedures/libc/gets.py file

### PR DESCRIPTION
**Pull request by rosnot**
add an angr/procedures/libc/gets.py file

### CODE REVIEW

**Comment by rhelmot** [comment]
What's the purpose of the delimiter logic? `gets` will receive up to the first newline, regardless of what characters it finds. Did you just copy this from the scanf code?

**Comment by rosnot** [comment]
@rhelmot oops, sorry. I referred to %s format and fgets source code. I will modify it.

**Comment by zardus** [comment]
I think this still has a few issues:

- It doesn't handle the case when there is no newline (i.e., the file ends).
- It concretizes the length of the read in all circumstances.

I think the second issue can be resolved by calling out to the `read` procedure (or to `state.posix.read(fd, dst, length)`), which handles symbolic read lengths. The first one is a bit trickier, though, and needs some thought...

**Comment by twizmwazin** [comment]
Obsolete

**Pull request closed without merging**
