### PR TITLE
Added Dockerfile.

### PR DESCRIPTION
**Pull request by Manouchehri**
I've placed the [Dockerfile from angr-dev](https://github.com/angr/angr-dev/blob/master/Dockerfile) inside this repository so we can have automated builds.

There's another step two, which I would do this myself if I could, but it needs to be done by someone who's listed as a team member on the repository of the angr.

To enable automated builds on each push, all that has to be done is create an account at [Docker Hub](https://hub.docker.com), pick automated build and point it towards angr's master branch.

2015-10-10-21 07 52-screenshot

Pictures for each step (use `/` instead of `/doc/`):

screenshot 2015-10-11 at 09 35 47

screenshot 2015-10-11 at 09 40 43

2015-10-10-21 07 52-screenshot

### CODE REVIEW

**Comment by rhelmot** [comment]
Who is "we" that wants automatic builds through Docker Hub?

There's already an automatic build system set up to run tests on pushes to all of the angr repositories on the ucsb seclab internal gitlab install, including some really complicated logic to do testing on branches other than master by synchronizing branches with the same name, etc. Am I misreading the intent of this PR?

**Comment by Manouchehri** [comment]
@rhelmot Sorry for the confusion, I am not suggesting Docker for doing build testing. It's meant for users like me that want to be able to `docker pull angr/angr` and just download/run the container instead having to built it manually. It saves quite a bit of time.

We [did this with radare2][https://github.com/radare/radare2/pull/3439] and it's become a [very popular choice among users](https://hub.docker.com/r/radare/radare2/) (there's been over 100,000 pulls in a mere few months).

**Comment by rhelmot** [comment]
Oh! Okay, that's a lot cooler. I'm in favor.

**Comment by Manouchehri** [comment]
Let me know if you have any trouble following my screenshots when you setup a Docker Hub account.

**Comment by rhelmot** [comment]
Issue: there's already an angr user on docker hub, and I don't know if it's controlled by anyone on the angr team! I didn't set it up, but maybe someone else did.

**Comment by rhelmot** [comment]
Additional issue: despite being an owner of the github angr organization, docker hub doesn't seem to see/let me select any angr repositories for setting up automated builds

**Comment by Manouchehri** [comment]
Paging @zardus for this.

**Comment by Manouchehri** [comment]
@rhelmot Did you remember to allow Docker to access your organizations https://docs.docker.com/docker-hub/github/

Give Docker org permissions

**Comment by Manouchehri** [comment]
@zardus has set everything up, looks good!

https://hub.docker.com/r/angr/angr/builds/

**Pull request merged**
