### PR TITLE
Fix duplicate definitions

### PR DESCRIPTION
**Pull request by zwimer**
Implements: https://github.com/angr/angr/issues/3684#issuecomment-1362486330

Before merging, the final duplicate needs to be addressed:

`def amd64g_create_mxcsr(state, sseround):`
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L943
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1362

### CODE REVIEW

**Comment by ltfish** [comment]
Why are we changing all indirect imports to absolute imports? Please focus this PR on fixing duplicate definitions.

**Comment by zwimer** [comment]
> Why are we changing all indirect imports to absolute imports? Please focus this PR on fixing duplicate definitions.

This was just because @rhelmot @twizmwazin and I were generally in consensus that absolute imports should be preferred to relative imports outside of a single `.`. I.e. `from ...a.b import c` should be removed in favor of `from angr.a.b import c`. So anytime I've been editing imports anyway in PRs, I've been updating these as well.

**Comment by zwimer** [comment]
> Please focus this PR on fixing duplicate definitions.

Are you asking me to revert the relative-to-absolute import changes?

**Comment by ltfish** [comment]
Instead of sneaking in these changes through irrelevant PRs, I'd rather apply them to new code or have another "overhaul"-style PR that changes all indirect imports.

**Comment by ltfish** [comment]
> > Please focus this PR on fixing duplicate definitions.
> 
> Are you asking me to revert the relative-to-absolute import changes?

Yes please!

**Review by ltfish — APPROVED** [review]

**Pull request merged**
