### PR TITLE
Support for explicit text modes "rt" and "wt" in fopen

### PR DESCRIPTION
**Pull request by Ben-4-Git**
Rarely modes rt or wt are used, but identical to r and w - see also https://stackoverflow.com/questions/23051062/open-files-in-rt-and-wt-modes

### CODE REVIEW

**Comment by ltfish** [comment]
Thank you!

**Comment by rhelmot** [comment]
I can't find any evidence that "rt" and "wt" are used anywhere but python's open function. From looking at the glibc source, there's no handling for a 't' character anywhere. Are you sure this is correct?

**Comment by ltfish** [comment]
This page shows up during my quick googling: http://www.kev.pulo.com.au/pp/RESOURCES/cplusplus/ref/cstdio/fopen.html

It's probably from some non-standard libc implementation.

**Comment by Ben-4-Git** [comment]
I came across it when solving this challenge:
https://www.root-me.org/de/Challenges/App-System/ELF32-Format-string-bug-basic-1

**Pull request merged**
