### PR TITLE
Prefer type annotations to comments + bug fixes

### PR DESCRIPTION
**Pull request by zwimer**
CI output should be double checked; I glanced at the type comments briefly but didn't thoroughly check if they were correct when converting the comments into annotations. Since annotations are comments this means there might be a `NameError` or something as a result. CI should fail if so though I believe.

I fixed some bugs such as comments that made no sense and comments that should have been `Optional` or used the wrong type `defaultdict -> DefaultDict` for example.

### CODE REVIEW

**Comment by zwimer** [comment]
@rhelmot The linter is failing with `undefined variable` for a lot of things; this is because some of the type annotations are things like `a: angr.foo` when in `angr/bar.py` whose imports do not contain `import angr`. I'm not quite sure where some of these types are coming from.

If you are able to fix these few that'd be appreciated; otherwise I can dedicate some time to this later.

**Comment by rhelmot** [comment]
stick em in quote marks

**Comment by zwimer** [comment]
> stick em in quote marks

That'll work. Would `mypy` and other things still break though since the objects they derive from would not be imported? I suppose we would just be where `master` is now with that though so I guess that's ok; not ideal, but not too objectionable either.

**Comment by zwimer** [comment]
Actually, some of these are just wrong; I'll just remove them.

**Review by rhelmot — APPROVED** [review]

**Pull request merged**
