### PR TITLE
Migration to NetworkX 2.x

### PR DESCRIPTION
**Pull request by tyb0807**
This follows #669 and answers #665. My goal is that all tests pass. However, `test_callable` and `test_accuracy` (and maybe some other tests as well) break even before the migration. Should I open another issue for this @rhelmot @ltfish ?

Thanks in advance

### CODE REVIEW

**Comment by danse-macabre** [comment]
@tyb0807 I wonder, how do you think this PR is close to be ready? Just wanted to tell, that I'm really looking forward for this PR to be merged, as the 2.0 version of *networkx* package does provide some cool features that I need to use in my works. In case you're short on time to work on it, I would like to lend a helping hand and finish it.

**Comment by tyb0807** [comment]
Hi. Things are quite ready in fact. The only test that doesn't pass is CFGAccurate. And I'm still waiting for @ltfish to fix it. So sorry for the delay :cry:. But if you really need it, maybe fish will make this his priority

**Comment by tyb0807** [comment]
Btw, @danse-macabre do you need help on this https://github.com/angr/angr/issues/580?

**Comment by ltfish** [comment]
> And I'm still waiting for @ltfish to fix it.

Just to confirm that this is true. It's somewhere in my todo list, but I have other stuff on my plate right now.

**Comment by tyb0807** [comment]
@ltfish hey tests pass now!

**Comment by ltfish** [comment]
ACK. I will merge them in after I make a final pass over your changes :-) Thanks a lot!

**Comment by ltfish** [comment]
Thank you so much!

**Pull request merged**
