### PR TITLE
Type Annotations for angr

### PR DESCRIPTION
**Pull request by fmagin**
Same procedure as angr/pyvex_#198.

EDIT by Fish: I edited the comment so that our CI doesn't accidentally pick up the wrong PyVEX commit to build against.

### CODE REVIEW

**Comment by ltfish** [comment]
Is this PR still WIP or is it good to be merged in?

Since we are dropping Python <=3.5, I believe we are ready to _heavily_ type annotate angr code and introduce a static type checker (mypy) into CI. Therefore, I'd like to get this PR merged so that I don't accidentally redo what you have done.

**Comment by fmagin** [comment]
Oh, I totally forgot this, I thought they had all been merged already. Will quickly rebase this, then it can be merged.

**Comment by ltfish** [comment]
Thank you so much for rebasing!

**Comment by ltfish** [comment]
Edited the PR and force-pushed to trigger the CI again. Sorry that our CI is being too smart this time...

**Pull request merged**
