### PR TITLE
WIP: apply magic permutation

### PR DESCRIPTION
**Pull request by schieb**
logging was broken (not printing) in `simuvex/procedures/__init__.py`
this magic fixes that but could it have unintended consequences?
¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by schieb** [comment]
Fix is currently incomplete (or wrong). I originally tested this by adding `l.setLevel(10)` in `simuvex/procedures/__init__.py`, which works (I can see logging output). However, after removing that and adding `logging.getLogger('simuvex.procedures').setLevel(10)` to my script, the behavior is back to broken.

**Comment by rhelmot** [comment]
You did say `logging.getLogger('simuvex.procedures').setLevel(10)` *above* the `import angr` line, right?

**Comment by schieb** [comment]
Well, I didn't do that originally but doing as you said makes it work. How strange...

Is it recommended to set logging levels before importing angr?

**Comment by rhelmot** [comment]
no... it's because the simprocedure import code happens *when* you do `import angr`, so the log level has to be set before then!

**Comment by schieb** [comment]
Oh that makes sense, thanks.

**Pull request merged**
