### PR TITLE
add timeout exploration technique

### PR DESCRIPTION
**Pull request by Kyle-Kyle**
https://github.com/angr/angr-doc/pull/422

a very slow timeout exploration technique.
maybe we should implement one correctly based on the discussion in #682

### CODE REVIEW

**Comment by rhelmot** [comment]
Kyle, is this PR a good starting point for future work? If so, could you rebase it? I'm sorry it got lost; I'll merge it this time.

**Comment by Kyle-Kyle** [comment]
I'll try to rebase it after S&P and resubmit the PR.

**Comment by Kyle-Kyle** [comment]
Can we disable `wrong-import-position`? That lint does not make sense to me. We need out-of-place imports for some specific files

**Comment by twizmwazin** [comment]
> For which files? Generally there is a way to better organize code such that this is not necessary. If it needs to be disabled, it'd be better to do it inline than globally.

**Comment by Kyle-Kyle** [comment]
for example: `angr/exploration_techniques/__init__.py`. It defines `ExplorationTechnique` that's needed by other files in the same directory and then import other files.

**Comment by twizmwazin** [comment]
A better way of handling this would be to create a base.py for the base class, and just importing it first.

**Comment by rhelmot** [comment]
That can be part of a separate pull request :)

**Comment by Kyle-Kyle** [comment]
how do I fix this? `"The following modules are not represented in the api docs`

**Comment by twizmwazin** [comment]
Add a line in [this](https://github.com/angr/angr-doc/blob/master/api-doc/source/angr.rst) file for your new module and cross-reference the PRs in the first posts so the CI uses them.

**Comment by Kyle-Kyle** [comment]
@twizmwazin I don't think the colorguard failure is caused by this PR. Can you rerun it and see whether it still fails?

**Pull request merged**
