### PR TITLE
Help remove tmp variables in AIL statements

### PR DESCRIPTION
**Pull request by Markakd**
- Propagator need some these handlers when it meets some conditions.
- Modified assignment handler in propagator engine to help remove tmp variables!

### CODE REVIEW

**Comment by ltfish** [comment]
You broke some test cases ;)

**Comment by Markakd** [comment]
In propagator AIL engine's tmp handler, I think it should only forward Register and Constant, Convert, StackBaseOffset or other expression simplification should be moved to AILSimplifier.

**Comment by ltfish** [comment]
Merged. Thanks!

**Comment by ltfish** [comment]
> In propagator AIL engine's tmp handler, I think it should only forward Register and Constant, Convert, StackBaseOffset or other expression simplification should be moved to AILSimplifier.

Apparently I don't remember the code enough to comment...

**Pull request merged**
