### PR TITLE
claripy: ccall: add adcx/adox support

### PR DESCRIPTION
**Pull request by zx2c4**
This wires up the VEX support for adcx/adox to claripy.

Requires https://github.com/angr/vex/pull/31 for VEX support.

### CODE REVIEW

**Comment by zx2c4** [comment]
https://github.com/angr/vex/pull/31 for VEX support.

**Comment by twizmwazin** [comment]
If you edit your initial comment to reference the vex PR, I can rerun the CI so that it uses the correct branch. The current failure is spurious, don't worry about it.

**Comment by zx2c4** [comment]
@twizmwazin initial comment adjusted.

**Comment by rhelmot** [comment]
Can you add a testcase? It doesn't have to be anything more complicated than running a single claripy op or x86 instruction and checking that the results are correct, a la https://github.com/angr/angr/blob/master/tests/test_vex.py or https://github.com/angr/angr/blob/master/tests/test_ops.py

**Comment by zx2c4** [comment]
Sure thing. Test case added in the commit I just force-pushed.

**Comment by rhelmot** [comment]
Cool, thanks!

**Pull request merged**
