### PR TITLE
Various minor CFG fixes

### PR DESCRIPTION
**Pull request by schieb**
~~Hopefully easier to read as well~~

### CODE REVIEW

**Comment by schieb** [comment]
@ltfish 
does it make sense to keep the checks in the cfg code that calls `resolve` knowing that subclasses of `IndirectJumpResolver` have access to a fucntion that does the same checks?

**Comment by ltfish** [comment]
> Does it make sense to keep the checks in the cfg code that calls resolve knowing that subclasses of IndirectJumpResolver have access to a fucntion that does the same checks?

No. Thanks for pointing it out. If you want, you can update your PR (or open a new one) to remove this check.

**Comment by schieb** [comment]
@ltfish Should be good to go

**Comment by ltfish** [comment]
Linting fails. See [here](https://travis-ci.org/angr/angr/jobs/269037546). With those fixed, this PR is good to go!

```
LINT FAILURE: angr/analyses/cfg/cfg_fast.py regressed to 9.96/9.99
... W:450,21: Redefining name 'o' from outer scope (line 20) (redefined-outer-name)
... W:2390,-1: String statement has no effect (pointless-string-statement)
... W: 21, 0: Unused AnnotatedCFG imported from annocfg (unused-import)
... W: 22, 0: Unused Blade imported from blade (unused-import)
... W: 24, 0: Unused SimSolverModeError imported from errors (unused-import)
... W: 26, 0: Unused Slicecutor imported from surveyors (unused-import)
```

**Comment by ltfish** [comment]
Thank you!

**Pull request merged**
