### PR TITLE
Merge identifier into angr

### PR DESCRIPTION
**Pull request by CodeMaxx**
@zardus @salls

### CODE REVIEW

**Comment by schieb** [comment]
A left over artifact from a merge conflict in `setup.py` caught my eye when browsing over the diff.

Function identification is a really interesting topic, I look forward to this merge, and hopefully some examples and docs :wink:.

**Comment by CodeMaxx** [comment]
@schieb Yes, I was just looking into that error

**Comment by ltfish** [comment]
I don't think adding `shellphish-afl` as an angr requirement is a good idea. Installing angr is already pretty slow. Thoughts?

**Comment by CodeMaxx** [comment]
@ltfish `identifier` has `shellphish-afl` as a dependency...

**Comment by zardus** [comment]
shellphish-afl is only really required for multi-cb bins. We can keep it out by default and just throw the warning if the binary is multi-cb.

**Comment by zardus** [comment]
Also, regarding the merge conflict, with the simuvex merge, I found that it really helped to remove setup.py, requirements.txt, and README.md from the to-be-merged repo before merging it in. No conflicts that way.

**Comment by ltfish** [comment]
In addition, as of now, identifier is only really tested on CGC binaries. We should really make it clear that users should not expect the current identifier to work for real-world binaries.

**Comment by ltfish** [comment]
@CodeMaxx for example, this is what you can do:

```
try:
    import shellphish-afl
except ImportError:
    print "Python package shellphish-afl is required to do XXX. Please install it before proceeding."
    sys.exit(-1)
```

**Comment by CodeMaxx** [comment]
Yeah I'll go ahead and do that

**Comment by zardus** [comment]
```sys.exit(-1)```.... Please please please don't do that.

**Comment by ltfish** [comment]
@zardus or `assert False`! I like it.

**Comment by CodeMaxx** [comment]
Moving to #496 . Doing a cleaner merge there preserving `git blame` outputs of identifier files

**Pull request closed without merging**
