### PR TITLE
changed _desc of memory/register read/write actions to easily identify their behavior

### PR DESCRIPTION
**Pull request by Lukas-Dresel**
For the following code: 
```python
import angr
proj = angr.Project('/bin/ls')
s = proj.factory.full_init_state(add_options={angr.options.TRACK_REGISTER_ACTIONS, angr.options.TRACK_MEMORY_ACTIONS})
sm = proj.factory.simulation_manager(s)
sm.step()
sm.step()
sm.step()
```

*BEFORE* When debugging:
```
In [1]: import monkeyhex

In [2]: sm.one_active.history.actions.hardcopy[-10:]
Out[2]: 
[<SimActionData 0x506000:12 reg/write>,
 <SimActionData 0x506000:13 reg/write>,
 <SimActionData 0x506016:1 reg/read>,
 <SimActionData 0x506016:3 reg/write>,
 <SimActionData 0x506016:4 reg/write>,
 <SimActionData 0x506016:5 reg/write>,
 <SimActionData 0x506016:6 reg/write>,
 <SimActionData 0x506016:7 reg/write>,
 <SimActionData 0x506016:9 mem/read>,
 <SimActionData 0x506016:11 reg/write>]
```

*AFTER* When debugging:
```
In [1]: import monkeyhex

In [2]: sm.one_active.history.actions.hardcopy[-10:]
Out[2]: 
[<SimActionData 0x506000:12 reg/write: cc_dep2  <<----  <SAO <BV64 0x0>>>,
 <SimActionData 0x506000:13 reg/write: rip  <<----  <SAO <BV64 0x506012>>>,
 <SimActionData 0x506016:1 reg/read: rsp  ---->>  <SAO <BV64 0x7fffffffffeff70>>>,
 <SimActionData 0x506016:3 reg/write: cc_op  <<----  <SAO <BV64 0x4>>>,
 <SimActionData 0x506016:4 reg/write: cc_dep1  <<----  <SAO <BV64 0x7fffffffffeff70>>>,
 <SimActionData 0x506016:5 reg/write: cc_dep2  <<----  <SAO <BV64 0x8>>>,
 <SimActionData 0x506016:6 reg/write: rsp  <<----  <SAO <BV64 0x7fffffffffeff78>>>,
 <SimActionData 0x506016:7 reg/write: rip  <<----  <SAO <BV64 0x50601a>>>,
 <SimActionData 0x506016:9 mem/read: <SAO <BV64 0x7fffffffffeff78>>  ---->>  <SAO <BV64 0xc000b0>>>,
 <SimActionData 0x506016:11 reg/write: rsp  <<----  <SAO <BV64 0x7fffffffffeff80>>>]
```

### CODE REVIEW

**Comment by rhelmot** [comment]
This is a good change - the only thing I'm going to ask for is that you use claripy's shallow render mechanism so we don't blow up anyone's console if there's a really really complicated AST

**Review by ltfish — APPROVED** [review]

**Comment by ltfish** [comment]
I agree with @rhelmot. I'll merge it once you limit the AST repr depth.

**Comment by Lukas-Dresel** [comment]
On it

**Comment by Lukas-Dresel** [comment]
What do you guys consider a reasonable limit? 300?

**Comment by ltfish** [comment]
300 is definitely too much... the default value seems good.

**Comment by Lukas-Dresel** [comment]
Sorry, yeah, i had 300 in mind for some reason for what i thought the default was. turns out is the current :D

**Comment by Lukas-Dresel** [comment]
Added.

**Comment by rhelmot** [comment]
Forcing you to do unrelated stuff in PRs is intentional. It is the only way we will eventually reach a codebase that lints at 100%, at which point things will be way less stupid.

**Pull request merged**
