### PR TITLE
Fix error in callsite stack arguments recovery

### PR DESCRIPTION
**Pull request by bluesadi**
Fix for #3868

### CODE REVIEW

**Comment by ltfish** [comment]
It fails CI, which probably means your fix is incorrect.

**Comment by bluesadi** [comment]
I will have a look at what went wrong

**Comment by bluesadi** [comment]
It should be ok (at least for all unit tests and the test binary I linked in #3868 ).

In my understanding (if it is correct), the previous callsite stack arguments recovery algorithm is kind of problematic. Stack definitions' offsets may be influenced by instructions unrelated to the callsite. Even though only performing RDA on the caller block, it can still be erroneous. For example, in `cgc_HIGHCOO.elf`, esp was substracted by 4 in the callsite block, which causes stack definitions' offsets becoming `[<Mem SP-0x8<4>>, <Mem SP-0xc<4>>, <Mem SP-0x10<4>>]`, not matched with the arg loc sequence (`[4, 8, ...]`).
image
Previous code passes the unit test ([test_decompiling_functions_with_unknown_simprocedures](https://github.com/angr/angr/blob/e802986e65a6a041d54d370e2fb0644df9094719/tests/test_decompiler.py#L2066)) just because some stack defs (i.e., `[<Mem SP-0x4<4>>, <Mem SP-0x8<4>>]`) happen to match the first two elements in arg loc sequence after setting [include_callsite_preds](https://github.com/angr/angr/blob/e802986e65a6a041d54d370e2fb0644df9094719/angr/analyses/calling_convention.py#L180) to True.

**Comment by bluesadi** [comment]
Btw, according to IDA's decompilation result, `cgc_allocate` function actually takes 3 arguments. Maybe the arg loc sequence should begin with 0 instead of 4?
image

**Comment by xxr0ss** [comment]
Really great work!
I tested this pr and it works well. I can't wait to see this pr get merged, BTW it'll be nice if you can add some testcases.

**Comment by ltfish** [comment]
> Really great work! I tested this pr and it works well. I can't wait to see this pr get merged, BTW it'll be nice if you can add some testcases.

It will take another few days because I am currently occupied by real-life matters, e.g., writing papers and proposals...

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
