### PR TITLE
Merge tracer into angr

### PR DESCRIPTION
**Pull request by tyb0807**
Hope that I've done things correctly this time @zardus

### CODE REVIEW

**Comment by zardus** [comment]
Almost there! Could you look into the couple of top-level files that were added? there's a `TODO.md` and an `info` directory, and it'd be great to not have them.

**Comment by tyb0807** [comment]
You mean like this?

**Comment by zardus** [comment]
Yep! Some other TODOs that come to mind:

1. Update driller, colorguard, and rex (as we discussed on slack).
2. Add a warning when tracer is used with a non-CGC binary.

**Comment by rhelmot** [comment]
3. Remove the tracer repository from CI

**Comment by tyb0807** [comment]
tracer should now be an otieg. Closing this

**Pull request closed without merging**
