### PR TITLE
Tests for Reachingdefinitions analysis

### PR DESCRIPTION
**Pull request by Pamplemousse**
Cleaned the old tests, and wrote new ones to compare to the captured behavior at this time.

### CODE REVIEW

**Comment by ltfish** [comment]
Can you please put back `main()` in `test_reachingdefinitions.py` so that I can run it easily when testing on my local machine?

**Comment by ltfish** [comment]
Fails on our CI: https://travis-ci.org/angr/angr/jobs/541588846

Note that the cwd of the CI runner is not necessarily the `tests` directory. You should always rely on the absolute path of the test file (`__file__`).

**Comment by Pamplemousse** [comment]
Well, I messed up my rebase and missed the new pickle files containing the data to be tested against...
Will see how it goes with them ^^

**Comment by ltfish** [comment]
Now your tests run, but the new test cases fail :)

**Comment by ltfish** [comment]
Tests pass! I'm merging it. Thanks!

**Pull request merged**
