### PR TITLE
Improve RDA's `DepGraph`

### PR DESCRIPTION
**Pull request by Pamplemousse**
* minor cleaning
  * minor additions (`nodes` and `predecessors`)
  * `add_dependencies_for_concrete_pointers_of` to fix the graph adding "static dependencies" when necessary

### CODE REVIEW

**Comment by Pamplemousse** [comment]
@ltfish, I need your opinion on this:

As of now, I set the `CodeLocation` of the pointed data to `None`: https://github.com/angr/angr/pull/2310/files#diff-d5cfa869a586a9ea29fd22ebd4ca52aaR151 .
Do you think it should be set it to `ExternalCodeLocation`? (does it make sense?)

**Comment by ltfish** [comment]
Remove [WIP] if you think it is ready.

**Comment by Pamplemousse** [comment]
I think it's "good for now":
  * Might get some minor adjustments in the future;
  * But is already pretty helpful as is.

**Review by ltfish — APPROVED** [review]

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
